#    Makefile for generating SOAP stubs for Steering Grid Service.
#
#    (C)Copyright 2002 The University of Manchester, United Kingdom,
#    all rights reserved.
#
#    This software is produced by the Supercomputing, Visualization &
#    e-Science Group, Manchester Computing, the Victoria University of
#    Manchester as part of the RealityGrid project.
#
#    This software has been tested with care but is not guaranteed for
#    any particular purpose. Neither the copyright holder, nor the
#    University of Manchester offer any warranties or representations,
#    nor do they accept any liabilities with respect to this software.
#
#    This software must not be used for commercial gain without the
#    written permission of the authors.
#    
#    This software must not be redistributed without the written
#    permission of the authors.
#
#    Permission is granted to modify this software, provided any
#    modifications are made freely available to the original authors.
# 
#    Supercomputing, Visualization & e-Science Group
#    Manchester Computing
#    University of Manchester
#    Manchester M13 9PL
#    
#    WWW:    http://www.sve.man.ac.uk  
#    email:  sve@man.ac.uk
#    Tel:    +44 161 275 6095
#    Fax:    +44 161 275 6800    
#
#    Initial version by:  A Porter, 23.7.2002
#
#------------------------------------------------------------------------

include ../Makefile.include

all: SGS.wsdl
	${JAVA} -cp ${SOAP_CLASS_PATH} wsdlcpp -c SGS.wsdl
	${SOAPCPP2} -c SGS.h
	cp -f soapStub.h soapH.h soapSGS.nsmap ../include/.
	cp -f soapC.c soapClient.c ../src/.
