# Makefile includes for the SWIG wrappings

# Set REG_WRAP to be a space separated list of languages to wrap
# or none for no wrapping.

REG_WRAP=none
#REG_WRAP=python java
#REG_WRAP=python perl tcl java

# swig
REG_SWIG=/usr/local/bin/swig

# python
REG_PYTHON_INC=-I/usr/include/python2.2 -I/usr/lib/python2.2/config/ -DHAVE_CONFIG_H

# java
REG_JAVA_PATH=/usr/java/j2sdk1.4.2_01
REG_JAVA_INC=-I${REG_JAVA_PATH}/include -I${REG_JAVA_PATH}/include/linux
JAVAC=${REG_JAVA_PATH}/bin/javac
