/* soapStub.h
   Generated by gSOAP 2.7.7 from all_hdrs.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_epr
#define SOAP_TYPE_epr (9)
/* epr */
struct epr
{
	char *wsa__Address;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sws__GetParamLogResponse
#define SOAP_TYPE_sws__GetParamLogResponse (10)
/* sws:GetParamLogResponse */
struct sws__GetParamLogResponse
{
	char *LogValues;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sws__RecordCheckpointResponse
#define SOAP_TYPE_sws__RecordCheckpointResponse (11)
/* sws:RecordCheckpointResponse */
struct sws__RecordCheckpointResponse
{
	char *_RecordCheckpointReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_Command
#define SOAP_TYPE_Command (12)
/* Command */
struct Command
{
	int Cmd_USCOREid;	/* required element of type xsd:int */
	char *Cmd_USCOREname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_supp_cmds
#define SOAP_TYPE_supp_cmds (13)
/* SOAP encoded array of Command schema type: */
struct supp_cmds
{
	struct Command *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_steerMessage
#define SOAP_TYPE_steerMessage (15)
/* steerMessage */
struct steerMessage
{
	struct supp_cmds Supported_USCOREcommands;	/* required element of type ArrayOfCommand */
};
#endif

#ifndef SOAP_TYPE_sws__AttachResponse
#define SOAP_TYPE_sws__AttachResponse (16)
/* sws:AttachResponse */
struct sws__AttachResponse
{
	struct steerMessage ReG_USCOREsteer_USCOREmessage;	/* RPC return element */	/* required element of type steerMessage */
};
#endif

#ifndef SOAP_TYPE_wsrp__DestroyResponse
#define SOAP_TYPE_wsrp__DestroyResponse (17)
/* wsrp:DestroyResponse */
struct wsrp__DestroyResponse
{
	void *_rubbish;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__PutParamLogResponse
#define SOAP_TYPE_sws__PutParamLogResponse (20)
/* sws:PutParamLogResponse */
struct sws__PutParamLogResponse
{
	void *_rubbish;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_GetResourcePropertyRequest
#define SOAP_TYPE_GetResourcePropertyRequest (21)
/* GetResourcePropertyRequest */
struct GetResourcePropertyRequest
{
	char *in_;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_wsrp__GetResourcePropertyResponse
#define SOAP_TYPE_wsrp__GetResourcePropertyResponse (22)
/* wsrp:GetResourcePropertyResponse */
struct wsrp__GetResourcePropertyResponse
{
	char *ResourceProperty;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_wsrp__ResourcePropertyStruct
#define SOAP_TYPE_wsrp__ResourcePropertyStruct (23)
/* wsrp:ResourcePropertyStruct */
struct wsrp__ResourcePropertyStruct
{
	char *ResourceProperty;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_wsrp__GetMultipleResourcePropertiesRequest
#define SOAP_TYPE_wsrp__GetMultipleResourcePropertiesRequest (24)
/* Sequence of wsrp:GetMultipleResourcePropertiesRequest schema type: */
struct wsrp__GetMultipleResourcePropertiesRequest
{
	struct wsrp__ResourcePropertyStruct *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_wsrp__SetResourcePropertiesResponse
#define SOAP_TYPE_wsrp__SetResourcePropertiesResponse (26)
/* wsrp:SetResourcePropertiesResponse */
struct wsrp__SetResourcePropertiesResponse
{
	void *rubbish;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__AddChildRequest
#define SOAP_TYPE_sws__AddChildRequest (27)
/* sws:AddChildRequest */
struct sws__AddChildRequest
{
	char *epr;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sws__AddChildResponse
#define SOAP_TYPE_sws__AddChildResponse (28)
/* sws:AddChildResponse */
struct sws__AddChildResponse
{
	void *rubbish;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__DetachResponse
#define SOAP_TYPE_sws__DetachResponse (29)
/* sws:DetachResponse */
struct sws__DetachResponse
{
	void *rubbish;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE___wsrp__GetResourceProperty
#define SOAP_TYPE___wsrp__GetResourceProperty (32)
/* Operation wrapper: */
struct __wsrp__GetResourceProperty
{
	char *wsrp__GetResourceProperty;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_wsrp__GetMultipleResourceProperties
#define SOAP_TYPE_wsrp__GetMultipleResourceProperties (34)
/* wsrp:GetMultipleResourceProperties */
struct wsrp__GetMultipleResourceProperties
{
	struct wsrp__GetMultipleResourcePropertiesRequest in;	/* required element of type wsrp:GetMultipleResourcePropertiesRequest */
};
#endif

#ifndef SOAP_TYPE_wsrp__SetResourceProperties
#define SOAP_TYPE_wsrp__SetResourceProperties (37)
/* wsrp:SetResourceProperties */
struct wsrp__SetResourceProperties
{
	char *wsrp__Insert;	/* optional element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE_wsrp__GetResourcePropertyDocument
#define SOAP_TYPE_wsrp__GetResourcePropertyDocument (39)
/* wsrp:GetResourcePropertyDocument */
struct wsrp__GetResourcePropertyDocument
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__AddChild
#define SOAP_TYPE_sws__AddChild (42)
/* sws:AddChild */
struct sws__AddChild
{
	struct sws__AddChildRequest __in;
};
#endif

#ifndef SOAP_TYPE_sws__Attach
#define SOAP_TYPE_sws__Attach (45)
/* sws:Attach */
struct sws__Attach
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__Detach
#define SOAP_TYPE_sws__Detach (48)
/* sws:Detach */
struct sws__Detach
{
	void *_param_1;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sws__RecordCheckpoint
#define SOAP_TYPE_sws__RecordCheckpoint (51)
/* sws:RecordCheckpoint */
struct sws__RecordCheckpoint
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sws__GetParamLog
#define SOAP_TYPE_sws__GetParamLog (54)
/* sws:GetParamLog */
struct sws__GetParamLog
{
	int in0;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_sws__PutParamLog
#define SOAP_TYPE_sws__PutParamLog (57)
/* sws:PutParamLog */
struct sws__PutParamLog
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_wsrp__Destroy
#define SOAP_TYPE_wsrp__Destroy (60)
/* wsrp:Destroy */
struct wsrp__Destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__GetParamLogResponse
#define SOAP_TYPE_sgs__GetParamLogResponse (61)
/* sgs:GetParamLogResponse */
struct sgs__GetParamLogResponse
{
	char *_GetParamLogReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__DetachResponse
#define SOAP_TYPE_sgs__DetachResponse (62)
/* sgs:DetachResponse */
struct sgs__DetachResponse
{
	char *_DetachReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppRecordChkpointResponse
#define SOAP_TYPE_sgs__AppRecordChkpointResponse (63)
/* sgs:AppRecordChkpointResponse */
struct sgs__AppRecordChkpointResponse
{
	char *_AppRecordChkpointReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__PutStatusResponse
#define SOAP_TYPE_sgs__PutStatusResponse (64)
/* sgs:PutStatusResponse */
struct sgs__PutStatusResponse
{
	char *_PutStatusReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__setServiceDataResponse
#define SOAP_TYPE_sgs__setServiceDataResponse (65)
/* sgs:setServiceDataResponse */
struct sgs__setServiceDataResponse
{
	char *_setServiceDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__PauseResponse
#define SOAP_TYPE_sgs__PauseResponse (66)
/* sgs:PauseResponse */
struct sgs__PauseResponse
{
	char *_PauseReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__findServiceDataResponse
#define SOAP_TYPE_sgs__findServiceDataResponse (67)
/* sgs:findServiceDataResponse */
struct sgs__findServiceDataResponse
{
	char *_findServiceDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__RestartResponse
#define SOAP_TYPE_sgs__RestartResponse (68)
/* sgs:RestartResponse */
struct sgs__RestartResponse
{
	char *_RestartReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__PutControlResponse
#define SOAP_TYPE_sgs__PutControlResponse (69)
/* sgs:PutControlResponse */
struct sgs__PutControlResponse
{
	char *_PutControlReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__ResumeResponse
#define SOAP_TYPE_sgs__ResumeResponse (70)
/* sgs:ResumeResponse */
struct sgs__ResumeResponse
{
	char *_ResumeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AttachResponse
#define SOAP_TYPE_sgs__AttachResponse (71)
/* sgs:AttachResponse */
struct sgs__AttachResponse
{
	char *_AttachReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__GetNotificationsResponse
#define SOAP_TYPE_sgs__GetNotificationsResponse (72)
/* sgs:GetNotificationsResponse */
struct sgs__GetNotificationsResponse
{
	char *_GetNotificationsReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__StopResponse
#define SOAP_TYPE_sgs__StopResponse (73)
/* sgs:StopResponse */
struct sgs__StopResponse
{
	char *_StopReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__GetControlResponse
#define SOAP_TYPE_sgs__GetControlResponse (74)
/* sgs:GetControlResponse */
struct sgs__GetControlResponse
{
	char *_GetControlReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__GetStatusResponse
#define SOAP_TYPE_sgs__GetStatusResponse (75)
/* sgs:GetStatusResponse */
struct sgs__GetStatusResponse
{
	char *_GetStatusReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppStopResponse
#define SOAP_TYPE_sgs__AppStopResponse (76)
/* sgs:AppStopResponse */
struct sgs__AppStopResponse
{
	char *_AppStopReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__destroyResponse
#define SOAP_TYPE_sgs__destroyResponse (77)
/* sgs:destroyResponse */
struct sgs__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__ClearStatusMsgQueueResponse
#define SOAP_TYPE_sgs__ClearStatusMsgQueueResponse (78)
/* sgs:ClearStatusMsgQueueResponse */
struct sgs__ClearStatusMsgQueueResponse
{
	char *_ClearStatusMsgQueueReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppPutLogResponse
#define SOAP_TYPE_sgs__AppPutLogResponse (79)
/* sgs:AppPutLogResponse */
struct sgs__AppPutLogResponse
{
	char *_AppPutLogReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__GetNthDataSourceResponse
#define SOAP_TYPE_sgs__GetNthDataSourceResponse (80)
/* sgs:GetNthDataSourceResponse */
struct sgs__GetNthDataSourceResponse
{
	char *_GetNthDataSourceReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppStartResponse
#define SOAP_TYPE_sgs__AppStartResponse (81)
/* sgs:AppStartResponse */
struct sgs__AppStartResponse
{
	char *_AppStartReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppDetachResponse
#define SOAP_TYPE_sgs__AppDetachResponse (82)
/* sgs:AppDetachResponse */
struct sgs__AppDetachResponse
{
	char *_AppDetachReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__Attach
#define SOAP_TYPE_sgs__Attach (85)
/* sgs:Attach */
struct sgs__Attach
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__GetStatus
#define SOAP_TYPE_sgs__GetStatus (88)
/* sgs:GetStatus */
struct sgs__GetStatus
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__Stop
#define SOAP_TYPE_sgs__Stop (91)
/* sgs:Stop */
struct sgs__Stop
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__ClearStatusMsgQueue
#define SOAP_TYPE_sgs__ClearStatusMsgQueue (94)
/* sgs:ClearStatusMsgQueue */
struct sgs__ClearStatusMsgQueue
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__Detach
#define SOAP_TYPE_sgs__Detach (97)
/* sgs:Detach */
struct sgs__Detach
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__Resume
#define SOAP_TYPE_sgs__Resume (100)
/* sgs:Resume */
struct sgs__Resume
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__AppRecordChkpoint
#define SOAP_TYPE_sgs__AppRecordChkpoint (103)
/* sgs:AppRecordChkpoint */
struct sgs__AppRecordChkpoint
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__PutStatus
#define SOAP_TYPE_sgs__PutStatus (106)
/* sgs:PutStatus */
struct sgs__PutStatus
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppStart
#define SOAP_TYPE_sgs__AppStart (109)
/* sgs:AppStart */
struct sgs__AppStart
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__GetParamLog
#define SOAP_TYPE_sgs__GetParamLog (112)
/* sgs:GetParamLog */
struct sgs__GetParamLog
{
	int in0;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_sgs__setServiceData
#define SOAP_TYPE_sgs__setServiceData (115)
/* sgs:setServiceData */
struct sgs__setServiceData
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppPutLog
#define SOAP_TYPE_sgs__AppPutLog (118)
/* sgs:AppPutLog */
struct sgs__AppPutLog
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__AppDetach
#define SOAP_TYPE_sgs__AppDetach (121)
/* sgs:AppDetach */
struct sgs__AppDetach
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__Pause
#define SOAP_TYPE_sgs__Pause (124)
/* sgs:Pause */
struct sgs__Pause
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__PutControl
#define SOAP_TYPE_sgs__PutControl (127)
/* sgs:PutControl */
struct sgs__PutControl
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__Restart
#define SOAP_TYPE_sgs__Restart (130)
/* sgs:Restart */
struct sgs__Restart
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__GetNthDataSource
#define SOAP_TYPE_sgs__GetNthDataSource (133)
/* sgs:GetNthDataSource */
struct sgs__GetNthDataSource
{
	int in0;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_sgs__findServiceData
#define SOAP_TYPE_sgs__findServiceData (136)
/* sgs:findServiceData */
struct sgs__findServiceData
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgs__destroy
#define SOAP_TYPE_sgs__destroy (139)
/* sgs:destroy */
struct sgs__destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__GetControl
#define SOAP_TYPE_sgs__GetControl (142)
/* sgs:GetControl */
struct sgs__GetControl
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__GetNotifications
#define SOAP_TYPE_sgs__GetNotifications (145)
/* sgs:GetNotifications */
struct sgs__GetNotifications
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgs__AppStop
#define SOAP_TYPE_sgs__AppStop (148)
/* sgs:AppStop */
struct sgs__AppStop
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgsf__createServiceResponse
#define SOAP_TYPE_sgsf__createServiceResponse (149)
/* sgsf:createServiceResponse */
struct sgsf__createServiceResponse
{
	char *_createServiceReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgsf__destroyResponse
#define SOAP_TYPE_sgsf__destroyResponse (150)
/* sgsf:destroyResponse */
struct sgsf__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgsf__registerSelfResponse
#define SOAP_TYPE_sgsf__registerSelfResponse (151)
/* sgsf:registerSelfResponse */
struct sgsf__registerSelfResponse
{
	char *_registerSelfReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgsf__registerSelf
#define SOAP_TYPE_sgsf__registerSelf (154)
/* sgsf:registerSelf */
struct sgsf__registerSelf
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgsf__destroy
#define SOAP_TYPE_sgsf__destroy (157)
/* sgsf:destroy */
struct sgsf__destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgsf__createService
#define SOAP_TYPE_sgsf__createService (160)
/* sgsf:createService */
struct sgsf__createService
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swsf__createSWSResourceResponse
#define SOAP_TYPE_swsf__createSWSResourceResponse (161)
/* swsf:createSWSResourceResponse */
struct swsf__createSWSResourceResponse
{
	struct epr wsa__EndpointReference;	/* RPC return element */	/* required element of type epr */
};
#endif

#ifndef SOAP_TYPE_swsf__createSWSResource
#define SOAP_TYPE_swsf__createSWSResource (164)
/* swsf:createSWSResource */
struct swsf__createSWSResource
{
	int timeToLive;	/* required element of type xsd:int */
	char *chkpointEPR;	/* optional element of type xsd:string */
	char *passPhrase;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgr__findServiceDataResponse
#define SOAP_TYPE_sgr__findServiceDataResponse (165)
/* sgr:findServiceDataResponse */
struct sgr__findServiceDataResponse
{
	char *_findServiceDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgr__addResponse
#define SOAP_TYPE_sgr__addResponse (166)
/* sgr:addResponse */
struct sgr__addResponse
{
	struct ArrayOf_USCORE_xsd_USCORE_string *_addReturn;	/* RPC return element */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ArrayOf_USCORE_xsd_USCORE_string
#define SOAP_TYPE_ArrayOf_USCORE_xsd_USCORE_string (167)
/* SOAP encoded array of xsd:string schema type: */
struct ArrayOf_USCORE_xsd_USCORE_string
{
	char **__ptr;
	int __size;
	int __offset;
};
#endif

#ifndef SOAP_TYPE_sgr__removeResponse
#define SOAP_TYPE_sgr__removeResponse (170)
/* sgr:removeResponse */
struct sgr__removeResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_sgr__remove
#define SOAP_TYPE_sgr__remove (173)
/* sgr:remove */
struct sgr__remove
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgr__add
#define SOAP_TYPE_sgr__add (176)
/* sgr:add */
struct sgr__add
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
	char *in2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_sgr__findServiceData
#define SOAP_TYPE_sgr__findServiceData (179)
/* sgr:findServiceData */
struct sgr__findServiceData
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__requestTerminationBeforeResponse
#define SOAP_TYPE_rgtf__requestTerminationBeforeResponse (180)
/* rgtf:requestTerminationBeforeResponse */
struct rgtf__requestTerminationBeforeResponse
{
	char *_requestTerminationBeforeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__findServiceDataResponse
#define SOAP_TYPE_rgtf__findServiceDataResponse (181)
/* rgtf:findServiceDataResponse */
struct rgtf__findServiceDataResponse
{
	char *_findServiceDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__findByHandleResponse
#define SOAP_TYPE_rgtf__findByHandleResponse (182)
/* rgtf:findByHandleResponse */
struct rgtf__findByHandleResponse
{
	char *_findByHandleReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__getActiveTreesResponse
#define SOAP_TYPE_rgtf__getActiveTreesResponse (183)
/* rgtf:getActiveTreesResponse */
struct rgtf__getActiveTreesResponse
{
	char *_getActiveTreesReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__createNewTreeResponse
#define SOAP_TYPE_rgtf__createNewTreeResponse (184)
/* rgtf:createNewTreeResponse */
struct rgtf__createNewTreeResponse
{
	char *_createNewTreeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__requestTerminationAfterResponse
#define SOAP_TYPE_rgtf__requestTerminationAfterResponse (185)
/* rgtf:requestTerminationAfterResponse */
struct rgtf__requestTerminationAfterResponse
{
	char *_requestTerminationAfterReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__destroyResponse
#define SOAP_TYPE_rgtf__destroyResponse (186)
/* rgtf:destroyResponse */
struct rgtf__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgtf__createNewTree
#define SOAP_TYPE_rgtf__createNewTree (189)
/* rgtf:createNewTree */
struct rgtf__createNewTree
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
	char *in2;	/* optional element of type xsd:string */
	char *in3;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__findByHandle
#define SOAP_TYPE_rgtf__findByHandle (192)
/* rgtf:findByHandle */
struct rgtf__findByHandle
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__destroy
#define SOAP_TYPE_rgtf__destroy (195)
/* rgtf:destroy */
struct rgtf__destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgtf__findServiceData
#define SOAP_TYPE_rgtf__findServiceData (198)
/* rgtf:findServiceData */
struct rgtf__findServiceData
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__getActiveTrees
#define SOAP_TYPE_rgtf__getActiveTrees (201)
/* rgtf:getActiveTrees */
struct rgtf__getActiveTrees
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgtf__requestTerminationBefore
#define SOAP_TYPE_rgtf__requestTerminationBefore (204)
/* rgtf:requestTerminationBefore */
struct rgtf__requestTerminationBefore
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgtf__requestTerminationAfter
#define SOAP_TYPE_rgtf__requestTerminationAfter (207)
/* rgtf:requestTerminationAfter */
struct rgtf__requestTerminationAfter
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getParentNodeResponse
#define SOAP_TYPE_rgt__getParentNodeResponse (208)
/* rgt:getParentNodeResponse */
struct rgt__getParentNodeResponse
{
	char *_getParentNodeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__requestTerminationAfterResponse
#define SOAP_TYPE_rgt__requestTerminationAfterResponse (209)
/* rgt:requestTerminationAfterResponse */
struct rgt__requestTerminationAfterResponse
{
	char *_requestTerminationAfterReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__addNodeResponse
#define SOAP_TYPE_rgt__addNodeResponse (210)
/* rgt:addNodeResponse */
struct rgt__addNodeResponse
{
	char *_addNodeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getCheckPointDataResponse
#define SOAP_TYPE_rgt__getCheckPointDataResponse (211)
/* rgt:getCheckPointDataResponse */
struct rgt__getCheckPointDataResponse
{
	char *_getCheckPointDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__findServiceDataResponse
#define SOAP_TYPE_rgt__findServiceDataResponse (212)
/* rgt:findServiceDataResponse */
struct rgt__findServiceDataResponse
{
	char *_findServiceDataReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__setCheckPointDataResponse
#define SOAP_TYPE_rgt__setCheckPointDataResponse (213)
/* rgt:setCheckPointDataResponse */
struct rgt__setCheckPointDataResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__getChildNodesResponse
#define SOAP_TYPE_rgt__getChildNodesResponse (214)
/* rgt:getChildNodesResponse */
struct rgt__getChildNodesResponse
{
	char *_getChildNodesReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__requestTerminationBeforeResponse
#define SOAP_TYPE_rgt__requestTerminationBeforeResponse (215)
/* rgt:requestTerminationBeforeResponse */
struct rgt__requestTerminationBeforeResponse
{
	char *_requestTerminationBeforeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getSteeringCommandsResponse
#define SOAP_TYPE_rgt__getSteeringCommandsResponse (216)
/* rgt:getSteeringCommandsResponse */
struct rgt__getSteeringCommandsResponse
{
	char *_getSteeringCommandsReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getInputFileResponse
#define SOAP_TYPE_rgt__getInputFileResponse (217)
/* rgt:getInputFileResponse */
struct rgt__getInputFileResponse
{
	char *_getInputFileReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__destroyResponse
#define SOAP_TYPE_rgt__destroyResponse (218)
/* rgt:destroyResponse */
struct rgt__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__requestTerminationAfter
#define SOAP_TYPE_rgt__requestTerminationAfter (221)
/* rgt:requestTerminationAfter */
struct rgt__requestTerminationAfter
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getChildNodes
#define SOAP_TYPE_rgt__getChildNodes (224)
/* rgt:getChildNodes */
struct rgt__getChildNodes
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__getInputFile
#define SOAP_TYPE_rgt__getInputFile (227)
/* rgt:getInputFile */
struct rgt__getInputFile
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__findServiceData
#define SOAP_TYPE_rgt__findServiceData (230)
/* rgt:findServiceData */
struct rgt__findServiceData
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__setCheckPointData
#define SOAP_TYPE_rgt__setCheckPointData (233)
/* rgt:setCheckPointData */
struct rgt__setCheckPointData
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__destroy
#define SOAP_TYPE_rgt__destroy (236)
/* rgt:destroy */
struct rgt__destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__getSteeringCommands
#define SOAP_TYPE_rgt__getSteeringCommands (239)
/* rgt:getSteeringCommands */
struct rgt__getSteeringCommands
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__requestTerminationBefore
#define SOAP_TYPE_rgt__requestTerminationBefore (242)
/* rgt:requestTerminationBefore */
struct rgt__requestTerminationBefore
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rgt__getCheckPointData
#define SOAP_TYPE_rgt__getCheckPointData (245)
/* rgt:getCheckPointData */
struct rgt__getCheckPointData
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__getParentNode
#define SOAP_TYPE_rgt__getParentNode (248)
/* rgt:getParentNode */
struct rgt__getParentNode
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_rgt__addNode
#define SOAP_TYPE_rgt__addNode (251)
/* rgt:addNode */
struct rgt__addNode
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
	char *in2;	/* optional element of type xsd:string */
	char *in3;	/* optional element of type xsd:string */
	char *in4;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_rsg__AddResponse
#define SOAP_TYPE_rsg__AddResponse (252)
/* rsg:AddResponse */
struct rsg__AddResponse
{
	struct epr wsa__EndpointReference;	/* RPC return element */	/* required element of type epr */
};
#endif

#ifndef SOAP_TYPE_rsg__Add
#define SOAP_TYPE_rsg__Add (255)
/* rsg:Add */
struct rsg__Add
{
	char *_in;	/* optional element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE_cpt__findByHandleResponse
#define SOAP_TYPE_cpt__findByHandleResponse (256)
/* cpt:findByHandleResponse */
struct cpt__findByHandleResponse
{
	char *_findByHandleReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cpt__getActiveTreesResponse
#define SOAP_TYPE_cpt__getActiveTreesResponse (257)
/* cpt:getActiveTreesResponse */
struct cpt__getActiveTreesResponse
{
	char *_getActiveTreesReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cpt__createNewTreeResponse
#define SOAP_TYPE_cpt__createNewTreeResponse (258)
/* cpt:createNewTreeResponse */
struct cpt__createNewTreeResponse
{
	char *_createNewTreeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cpt__destroyResponse
#define SOAP_TYPE_cpt__destroyResponse (259)
/* cpt:destroyResponse */
struct cpt__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_cpt__createNewTree
#define SOAP_TYPE_cpt__createNewTree (262)
/* cpt:createNewTree */
struct cpt__createNewTree
{
	char *in0;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cpt__findByHandle
#define SOAP_TYPE_cpt__findByHandle (265)
/* cpt:findByHandle */
struct cpt__findByHandle
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cpt__Destroy
#define SOAP_TYPE_cpt__Destroy (268)
/* cpt:Destroy */
struct cpt__Destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cpt__getActiveTrees
#define SOAP_TYPE_cpt__getActiveTrees (271)
/* cpt:getActiveTrees */
struct cpt__getActiveTrees
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cptn__addNodeResponse
#define SOAP_TYPE_cptn__addNodeResponse (272)
/* cptn:addNodeResponse */
struct cptn__addNodeResponse
{
	char *_addNodeReturn;	/* RPC return element */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cptn__destroyResponse
#define SOAP_TYPE_cptn__destroyResponse (273)
/* cptn:destroyResponse */
struct cptn__destroyResponse
{
	void *_;	/* RPC return element */	/* transient */
};
#endif

#ifndef SOAP_TYPE_cptn__Destroy
#define SOAP_TYPE_cptn__Destroy (276)
/* cptn:Destroy */
struct cptn__Destroy
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cptn__addNode
#define SOAP_TYPE_cptn__addNode (279)
/* cptn:addNode */
struct cptn__addNode
{
	char *in0;	/* optional element of type xsd:string */
	char *in1;	/* optional element of type xsd:string */
	char *in2;	/* optional element of type xsd:string */
	char *in3;	/* optional element of type xsd:string */
	char *in4;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_stringWithAttr
#define SOAP_TYPE_stringWithAttr (280)
/* Primitive stringWithAttr schema type: */
struct stringWithAttr
{
	char *__item;
	char *Type;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_UsernameToken
#define SOAP_TYPE_UsernameToken (281)
/* UsernameToken */
struct UsernameToken
{
	char *wsse__Username;	/* optional element of type xsd:string */
	struct stringWithAttr wsse__Password;	/* required element of type stringWithAttr */
	char *wsse__Nonce;	/* optional element of type xsd:string */
	char *wsu__Created;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_Security
#define SOAP_TYPE_Security (282)
/* Security */
struct Security
{
	struct UsernameToken wsse__UsernameToken;	/* required element of type UsernameToken */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (283)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *wsa__To;	/* optional element of type xsd:string */
	struct Security wsse__Security;	/* required element of type Security */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (284)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (286)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (287)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (288)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
typedef char *xsd__string;
#endif

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (7)
typedef int xsd__int;
#endif

#ifndef SOAP_TYPE_XML
#define SOAP_TYPE_XML (8)
typedef char *XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __wsrp__GetResourceProperty(struct soap*, char *wsrp__GetResourceProperty, char **out_);

SOAP_FMAC5 int SOAP_FMAC6 wsrp__GetMultipleResourceProperties(struct soap*, struct wsrp__GetMultipleResourcePropertiesRequest in, char **_out);

SOAP_FMAC5 int SOAP_FMAC6 wsrp__SetResourceProperties(struct soap*, char *wsrp__Insert, struct wsrp__SetResourcePropertiesResponse *_out);

SOAP_FMAC5 int SOAP_FMAC6 wsrp__GetResourcePropertyDocument(struct soap*, void *_, char **out_);

SOAP_FMAC5 int SOAP_FMAC6 sws__AddChild(struct soap*, struct sws__AddChildRequest __in, struct sws__AddChildResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 sws__Attach(struct soap*, void *_, struct sws__AttachResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 sws__Detach(struct soap*, void *_param_1, struct sws__DetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sws__RecordCheckpoint(struct soap*, char *in0, char *in1, struct sws__RecordCheckpointResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sws__GetParamLog(struct soap*, int in0, struct sws__GetParamLogResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 sws__PutParamLog(struct soap*, char *in0, struct sws__PutParamLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 wsrp__Destroy(struct soap*, void *_, struct wsrp__DestroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Attach(struct soap*, void *_, struct sgs__AttachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__GetStatus(struct soap*, void *_, struct sgs__GetStatusResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Stop(struct soap*, void *_, struct sgs__StopResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__ClearStatusMsgQueue(struct soap*, void *_, struct sgs__ClearStatusMsgQueueResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Detach(struct soap*, void *_, struct sgs__DetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Resume(struct soap*, void *_, struct sgs__ResumeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__AppRecordChkpoint(struct soap*, char *in0, char *in1, struct sgs__AppRecordChkpointResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__PutStatus(struct soap*, char *in0, struct sgs__PutStatusResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__AppStart(struct soap*, void *_, struct sgs__AppStartResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__GetParamLog(struct soap*, int in0, struct sgs__GetParamLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__setServiceData(struct soap*, char *in0, struct sgs__setServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__AppPutLog(struct soap*, char *in0, struct sgs__AppPutLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__AppDetach(struct soap*, void *_, struct sgs__AppDetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Pause(struct soap*, void *_, struct sgs__PauseResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__PutControl(struct soap*, char *in0, struct sgs__PutControlResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__Restart(struct soap*, char *in0, struct sgs__RestartResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__GetNthDataSource(struct soap*, int in0, struct sgs__GetNthDataSourceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__findServiceData(struct soap*, char *in0, struct sgs__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__destroy(struct soap*, void *_, struct sgs__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__GetControl(struct soap*, void *_, struct sgs__GetControlResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__GetNotifications(struct soap*, void *_, struct sgs__GetNotificationsResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgs__AppStop(struct soap*, void *_, struct sgs__AppStopResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgsf__registerSelf(struct soap*, char *in0, char *in1, struct sgsf__registerSelfResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgsf__destroy(struct soap*, void *_, struct sgsf__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgsf__createService(struct soap*, char *in0, char *in1, struct sgsf__createServiceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 swsf__createSWSResource(struct soap*, int timeToLive, char *chkpointEPR, char *passPhrase, struct swsf__createSWSResourceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgr__remove(struct soap*, char *in0, struct sgr__removeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgr__add(struct soap*, char *in0, char *in1, char *in2, struct sgr__addResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 sgr__findServiceData(struct soap*, char *in0, struct sgr__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__createNewTree(struct soap*, char *in0, char *in1, char *in2, char *in3, struct rgtf__createNewTreeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__findByHandle(struct soap*, char *in0, char *in1, struct rgtf__findByHandleResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__destroy(struct soap*, void *_, struct rgtf__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__findServiceData(struct soap*, char *in0, struct rgtf__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__getActiveTrees(struct soap*, void *_, struct rgtf__getActiveTreesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__requestTerminationBefore(struct soap*, char *in0, struct rgtf__requestTerminationBeforeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgtf__requestTerminationAfter(struct soap*, char *in0, struct rgtf__requestTerminationAfterResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__requestTerminationAfter(struct soap*, char *in0, struct rgt__requestTerminationAfterResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__getChildNodes(struct soap*, void *_, struct rgt__getChildNodesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__getInputFile(struct soap*, void *_, struct rgt__getInputFileResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__findServiceData(struct soap*, char *in0, struct rgt__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__setCheckPointData(struct soap*, void *_, struct rgt__setCheckPointDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__destroy(struct soap*, void *_, struct rgt__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__getSteeringCommands(struct soap*, void *_, struct rgt__getSteeringCommandsResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__requestTerminationBefore(struct soap*, char *in0, struct rgt__requestTerminationBeforeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__getCheckPointData(struct soap*, void *_, struct rgt__getCheckPointDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__getParentNode(struct soap*, void *_, struct rgt__getParentNodeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rgt__addNode(struct soap*, char *in0, char *in1, char *in2, char *in3, char *in4, struct rgt__addNodeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 rsg__Add(struct soap*, char *_in, struct rsg__AddResponse *_out);

SOAP_FMAC5 int SOAP_FMAC6 cpt__createNewTree(struct soap*, char *in0, struct cpt__createNewTreeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 cpt__findByHandle(struct soap*, char *in0, char *in1, struct cpt__findByHandleResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 cpt__Destroy(struct soap*, void *_, struct cpt__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 cpt__getActiveTrees(struct soap*, void *_, struct cpt__getActiveTreesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 cptn__Destroy(struct soap*, void *_, struct cptn__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 cptn__addNode(struct soap*, char *in0, char *in1, char *in2, char *in3, char *in4, struct cptn__addNodeResponse *out);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___wsrp__GetResourceProperty(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *wsrp__GetResourceProperty, char **out_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wsrp__GetMultipleResourceProperties(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsrp__GetMultipleResourcePropertiesRequest in, char **_out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wsrp__SetResourceProperties(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *wsrp__Insert, struct wsrp__SetResourcePropertiesResponse *_out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wsrp__GetResourcePropertyDocument(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, char **out_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__AddChild(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct sws__AddChildRequest __in, struct sws__AddChildResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__Attach(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sws__AttachResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__Detach(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_param_1, struct sws__DetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__RecordCheckpoint(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct sws__RecordCheckpointResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__GetParamLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, int in0, struct sws__GetParamLogResponse *out_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sws__PutParamLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sws__PutParamLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wsrp__Destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct wsrp__DestroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Attach(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__AttachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__GetStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__GetStatusResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Stop(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__StopResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__ClearStatusMsgQueue(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__ClearStatusMsgQueueResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Detach(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__DetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Resume(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__ResumeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__AppRecordChkpoint(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct sgs__AppRecordChkpointResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__PutStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__PutStatusResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__AppStart(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__AppStartResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__GetParamLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, int in0, struct sgs__GetParamLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__setServiceData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__setServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__AppPutLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__AppPutLogResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__AppDetach(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__AppDetachResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Pause(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__PauseResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__PutControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__PutControlResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__Restart(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__RestartResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__GetNthDataSource(struct soap *soap, const char *soap_endpoint, const char *soap_action, int in0, struct sgs__GetNthDataSourceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__findServiceData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgs__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__GetControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__GetControlResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__GetNotifications(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__GetNotificationsResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgs__AppStop(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgs__AppStopResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgsf__registerSelf(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct sgsf__registerSelfResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgsf__destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct sgsf__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgsf__createService(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct sgsf__createServiceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_swsf__createSWSResource(struct soap *soap, const char *soap_endpoint, const char *soap_action, int timeToLive, char *chkpointEPR, char *passPhrase, struct swsf__createSWSResourceResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgr__remove(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgr__removeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgr__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, char *in2, struct sgr__addResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_sgr__findServiceData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct sgr__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__createNewTree(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, char *in2, char *in3, struct rgtf__createNewTreeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__findByHandle(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct rgtf__findByHandleResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgtf__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__findServiceData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgtf__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__getActiveTrees(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgtf__getActiveTreesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__requestTerminationBefore(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgtf__requestTerminationBeforeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgtf__requestTerminationAfter(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgtf__requestTerminationAfterResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__requestTerminationAfter(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgt__requestTerminationAfterResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__getChildNodes(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__getChildNodesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__getInputFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__getInputFileResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__findServiceData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgt__findServiceDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__setCheckPointData(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__setCheckPointDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__getSteeringCommands(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__getSteeringCommandsResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__requestTerminationBefore(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct rgt__requestTerminationBeforeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__getCheckPointData(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__getCheckPointDataResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__getParentNode(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct rgt__getParentNodeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rgt__addNode(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, char *in2, char *in3, char *in4, struct rgt__addNodeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_rsg__Add(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in, struct rsg__AddResponse *_out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cpt__createNewTree(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, struct cpt__createNewTreeResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cpt__findByHandle(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, struct cpt__findByHandleResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cpt__Destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct cpt__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cpt__getActiveTrees(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct cpt__getActiveTreesResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cptn__Destroy(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct cptn__destroyResponse *out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cptn__addNode(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *in0, char *in1, char *in2, char *in3, char *in4, struct cptn__addNodeResponse *out);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsrp__GetResourceProperty(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_wsrp__GetMultipleResourceProperties(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_wsrp__SetResourceProperties(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_wsrp__GetResourcePropertyDocument(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__AddChild(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__Attach(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__Detach(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__RecordCheckpoint(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__GetParamLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sws__PutParamLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_wsrp__Destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Attach(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__GetStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Stop(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__ClearStatusMsgQueue(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Detach(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Resume(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__AppRecordChkpoint(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__PutStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__AppStart(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__GetParamLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__setServiceData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__AppPutLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__AppDetach(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Pause(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__PutControl(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__Restart(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__GetNthDataSource(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__findServiceData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__GetControl(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__GetNotifications(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgs__AppStop(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgsf__registerSelf(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgsf__destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgsf__createService(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swsf__createSWSResource(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgr__remove(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgr__add(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_sgr__findServiceData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__createNewTree(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__findByHandle(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__findServiceData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__getActiveTrees(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__requestTerminationBefore(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgtf__requestTerminationAfter(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__requestTerminationAfter(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__getChildNodes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__getInputFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__findServiceData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__setCheckPointData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__getSteeringCommands(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__requestTerminationBefore(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__getCheckPointData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__getParentNode(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rgt__addNode(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rsg__Add(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cpt__createNewTree(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cpt__findByHandle(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cpt__Destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cpt__getActiveTrees(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cptn__Destroy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cptn__addNode(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
