/* soapH.h
   Generated by gSOAP 2.7.13 from all_hdrs.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (8)
#endif

#define soap_default_xsd__int(soap, a) soap_default_int(soap, a)


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_Security
#define SOAP_TYPE_Security (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Security(struct soap*, struct Security *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Security(struct soap*, const struct Security *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_Security(struct soap*, const struct Security *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Security(struct soap*, const char*, int, const struct Security *, const char*);
SOAP_FMAC3 struct Security * SOAP_FMAC4 soap_get_Security(struct soap*, struct Security *, const char*, const char*);
SOAP_FMAC3 struct Security * SOAP_FMAC4 soap_in_Security(struct soap*, const char*, struct Security *, const char*);

#ifndef SOAP_TYPE_UsernameToken
#define SOAP_TYPE_UsernameToken (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_UsernameToken(struct soap*, struct UsernameToken *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_UsernameToken(struct soap*, const struct UsernameToken *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_UsernameToken(struct soap*, const struct UsernameToken *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_UsernameToken(struct soap*, const char*, int, const struct UsernameToken *, const char*);
SOAP_FMAC3 struct UsernameToken * SOAP_FMAC4 soap_get_UsernameToken(struct soap*, struct UsernameToken *, const char*, const char*);
SOAP_FMAC3 struct UsernameToken * SOAP_FMAC4 soap_in_UsernameToken(struct soap*, const char*, struct UsernameToken *, const char*);

#ifndef SOAP_TYPE_stringWithAttr
#define SOAP_TYPE_stringWithAttr (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_stringWithAttr(struct soap*, struct stringWithAttr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_stringWithAttr(struct soap*, const struct stringWithAttr *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_stringWithAttr(struct soap*, const struct stringWithAttr *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_stringWithAttr(struct soap*, const char*, int, const struct stringWithAttr *, const char*);
SOAP_FMAC3 struct stringWithAttr * SOAP_FMAC4 soap_get_stringWithAttr(struct soap*, struct stringWithAttr *, const char*, const char*);
SOAP_FMAC3 struct stringWithAttr * SOAP_FMAC4 soap_in_stringWithAttr(struct soap*, const char*, struct stringWithAttr *, const char*);

#ifndef SOAP_TYPE_cptn__addNode
#define SOAP_TYPE_cptn__addNode (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cptn__addNode(struct soap*, struct cptn__addNode *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cptn__addNode(struct soap*, const struct cptn__addNode *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cptn__addNode(struct soap*, const struct cptn__addNode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cptn__addNode(struct soap*, const char*, int, const struct cptn__addNode *, const char*);
SOAP_FMAC3 struct cptn__addNode * SOAP_FMAC4 soap_get_cptn__addNode(struct soap*, struct cptn__addNode *, const char*, const char*);
SOAP_FMAC3 struct cptn__addNode * SOAP_FMAC4 soap_in_cptn__addNode(struct soap*, const char*, struct cptn__addNode *, const char*);

#ifndef SOAP_TYPE_cptn__Destroy
#define SOAP_TYPE_cptn__Destroy (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cptn__Destroy(struct soap*, struct cptn__Destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cptn__Destroy(struct soap*, const struct cptn__Destroy *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cptn__Destroy(struct soap*, const struct cptn__Destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cptn__Destroy(struct soap*, const char*, int, const struct cptn__Destroy *, const char*);
SOAP_FMAC3 struct cptn__Destroy * SOAP_FMAC4 soap_get_cptn__Destroy(struct soap*, struct cptn__Destroy *, const char*, const char*);
SOAP_FMAC3 struct cptn__Destroy * SOAP_FMAC4 soap_in_cptn__Destroy(struct soap*, const char*, struct cptn__Destroy *, const char*);

#ifndef SOAP_TYPE_cptn__destroyResponse
#define SOAP_TYPE_cptn__destroyResponse (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cptn__destroyResponse(struct soap*, struct cptn__destroyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cptn__destroyResponse(struct soap*, const struct cptn__destroyResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cptn__destroyResponse(struct soap*, const struct cptn__destroyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cptn__destroyResponse(struct soap*, const char*, int, const struct cptn__destroyResponse *, const char*);
SOAP_FMAC3 struct cptn__destroyResponse * SOAP_FMAC4 soap_get_cptn__destroyResponse(struct soap*, struct cptn__destroyResponse *, const char*, const char*);
SOAP_FMAC3 struct cptn__destroyResponse * SOAP_FMAC4 soap_in_cptn__destroyResponse(struct soap*, const char*, struct cptn__destroyResponse *, const char*);

#ifndef SOAP_TYPE_cptn__addNodeResponse
#define SOAP_TYPE_cptn__addNodeResponse (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cptn__addNodeResponse(struct soap*, struct cptn__addNodeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cptn__addNodeResponse(struct soap*, const struct cptn__addNodeResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cptn__addNodeResponse(struct soap*, const struct cptn__addNodeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cptn__addNodeResponse(struct soap*, const char*, int, const struct cptn__addNodeResponse *, const char*);
SOAP_FMAC3 struct cptn__addNodeResponse * SOAP_FMAC4 soap_get_cptn__addNodeResponse(struct soap*, struct cptn__addNodeResponse *, const char*, const char*);
SOAP_FMAC3 struct cptn__addNodeResponse * SOAP_FMAC4 soap_in_cptn__addNodeResponse(struct soap*, const char*, struct cptn__addNodeResponse *, const char*);

#ifndef SOAP_TYPE_cpt__getActiveTrees
#define SOAP_TYPE_cpt__getActiveTrees (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__getActiveTrees(struct soap*, struct cpt__getActiveTrees *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__getActiveTrees(struct soap*, const struct cpt__getActiveTrees *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__getActiveTrees(struct soap*, const struct cpt__getActiveTrees *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__getActiveTrees(struct soap*, const char*, int, const struct cpt__getActiveTrees *, const char*);
SOAP_FMAC3 struct cpt__getActiveTrees * SOAP_FMAC4 soap_get_cpt__getActiveTrees(struct soap*, struct cpt__getActiveTrees *, const char*, const char*);
SOAP_FMAC3 struct cpt__getActiveTrees * SOAP_FMAC4 soap_in_cpt__getActiveTrees(struct soap*, const char*, struct cpt__getActiveTrees *, const char*);

#ifndef SOAP_TYPE_cpt__Destroy
#define SOAP_TYPE_cpt__Destroy (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__Destroy(struct soap*, struct cpt__Destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__Destroy(struct soap*, const struct cpt__Destroy *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__Destroy(struct soap*, const struct cpt__Destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__Destroy(struct soap*, const char*, int, const struct cpt__Destroy *, const char*);
SOAP_FMAC3 struct cpt__Destroy * SOAP_FMAC4 soap_get_cpt__Destroy(struct soap*, struct cpt__Destroy *, const char*, const char*);
SOAP_FMAC3 struct cpt__Destroy * SOAP_FMAC4 soap_in_cpt__Destroy(struct soap*, const char*, struct cpt__Destroy *, const char*);

#ifndef SOAP_TYPE_cpt__findByHandle
#define SOAP_TYPE_cpt__findByHandle (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__findByHandle(struct soap*, struct cpt__findByHandle *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__findByHandle(struct soap*, const struct cpt__findByHandle *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__findByHandle(struct soap*, const struct cpt__findByHandle *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__findByHandle(struct soap*, const char*, int, const struct cpt__findByHandle *, const char*);
SOAP_FMAC3 struct cpt__findByHandle * SOAP_FMAC4 soap_get_cpt__findByHandle(struct soap*, struct cpt__findByHandle *, const char*, const char*);
SOAP_FMAC3 struct cpt__findByHandle * SOAP_FMAC4 soap_in_cpt__findByHandle(struct soap*, const char*, struct cpt__findByHandle *, const char*);

#ifndef SOAP_TYPE_cpt__createNewTree
#define SOAP_TYPE_cpt__createNewTree (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__createNewTree(struct soap*, struct cpt__createNewTree *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__createNewTree(struct soap*, const struct cpt__createNewTree *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__createNewTree(struct soap*, const struct cpt__createNewTree *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__createNewTree(struct soap*, const char*, int, const struct cpt__createNewTree *, const char*);
SOAP_FMAC3 struct cpt__createNewTree * SOAP_FMAC4 soap_get_cpt__createNewTree(struct soap*, struct cpt__createNewTree *, const char*, const char*);
SOAP_FMAC3 struct cpt__createNewTree * SOAP_FMAC4 soap_in_cpt__createNewTree(struct soap*, const char*, struct cpt__createNewTree *, const char*);

#ifndef SOAP_TYPE_cpt__destroyResponse
#define SOAP_TYPE_cpt__destroyResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__destroyResponse(struct soap*, struct cpt__destroyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__destroyResponse(struct soap*, const struct cpt__destroyResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__destroyResponse(struct soap*, const struct cpt__destroyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__destroyResponse(struct soap*, const char*, int, const struct cpt__destroyResponse *, const char*);
SOAP_FMAC3 struct cpt__destroyResponse * SOAP_FMAC4 soap_get_cpt__destroyResponse(struct soap*, struct cpt__destroyResponse *, const char*, const char*);
SOAP_FMAC3 struct cpt__destroyResponse * SOAP_FMAC4 soap_in_cpt__destroyResponse(struct soap*, const char*, struct cpt__destroyResponse *, const char*);

#ifndef SOAP_TYPE_cpt__createNewTreeResponse
#define SOAP_TYPE_cpt__createNewTreeResponse (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__createNewTreeResponse(struct soap*, struct cpt__createNewTreeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__createNewTreeResponse(struct soap*, const struct cpt__createNewTreeResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__createNewTreeResponse(struct soap*, const struct cpt__createNewTreeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__createNewTreeResponse(struct soap*, const char*, int, const struct cpt__createNewTreeResponse *, const char*);
SOAP_FMAC3 struct cpt__createNewTreeResponse * SOAP_FMAC4 soap_get_cpt__createNewTreeResponse(struct soap*, struct cpt__createNewTreeResponse *, const char*, const char*);
SOAP_FMAC3 struct cpt__createNewTreeResponse * SOAP_FMAC4 soap_in_cpt__createNewTreeResponse(struct soap*, const char*, struct cpt__createNewTreeResponse *, const char*);

#ifndef SOAP_TYPE_cpt__getActiveTreesResponse
#define SOAP_TYPE_cpt__getActiveTreesResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__getActiveTreesResponse(struct soap*, struct cpt__getActiveTreesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__getActiveTreesResponse(struct soap*, const struct cpt__getActiveTreesResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__getActiveTreesResponse(struct soap*, const struct cpt__getActiveTreesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__getActiveTreesResponse(struct soap*, const char*, int, const struct cpt__getActiveTreesResponse *, const char*);
SOAP_FMAC3 struct cpt__getActiveTreesResponse * SOAP_FMAC4 soap_get_cpt__getActiveTreesResponse(struct soap*, struct cpt__getActiveTreesResponse *, const char*, const char*);
SOAP_FMAC3 struct cpt__getActiveTreesResponse * SOAP_FMAC4 soap_in_cpt__getActiveTreesResponse(struct soap*, const char*, struct cpt__getActiveTreesResponse *, const char*);

#ifndef SOAP_TYPE_cpt__findByHandleResponse
#define SOAP_TYPE_cpt__findByHandleResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_cpt__findByHandleResponse(struct soap*, struct cpt__findByHandleResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_cpt__findByHandleResponse(struct soap*, const struct cpt__findByHandleResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_cpt__findByHandleResponse(struct soap*, const struct cpt__findByHandleResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_cpt__findByHandleResponse(struct soap*, const char*, int, const struct cpt__findByHandleResponse *, const char*);
SOAP_FMAC3 struct cpt__findByHandleResponse * SOAP_FMAC4 soap_get_cpt__findByHandleResponse(struct soap*, struct cpt__findByHandleResponse *, const char*, const char*);
SOAP_FMAC3 struct cpt__findByHandleResponse * SOAP_FMAC4 soap_in_cpt__findByHandleResponse(struct soap*, const char*, struct cpt__findByHandleResponse *, const char*);

#ifndef SOAP_TYPE_rsg__Add
#define SOAP_TYPE_rsg__Add (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_rsg__Add(struct soap*, struct rsg__Add *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_rsg__Add(struct soap*, const struct rsg__Add *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_rsg__Add(struct soap*, const struct rsg__Add *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_rsg__Add(struct soap*, const char*, int, const struct rsg__Add *, const char*);
SOAP_FMAC3 struct rsg__Add * SOAP_FMAC4 soap_get_rsg__Add(struct soap*, struct rsg__Add *, const char*, const char*);
SOAP_FMAC3 struct rsg__Add * SOAP_FMAC4 soap_in_rsg__Add(struct soap*, const char*, struct rsg__Add *, const char*);

#ifndef SOAP_TYPE_rsg__AddResponse
#define SOAP_TYPE_rsg__AddResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_rsg__AddResponse(struct soap*, struct rsg__AddResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_rsg__AddResponse(struct soap*, const struct rsg__AddResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_rsg__AddResponse(struct soap*, const struct rsg__AddResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_rsg__AddResponse(struct soap*, const char*, int, const struct rsg__AddResponse *, const char*);
SOAP_FMAC3 struct rsg__AddResponse * SOAP_FMAC4 soap_get_rsg__AddResponse(struct soap*, struct rsg__AddResponse *, const char*, const char*);
SOAP_FMAC3 struct rsg__AddResponse * SOAP_FMAC4 soap_in_rsg__AddResponse(struct soap*, const char*, struct rsg__AddResponse *, const char*);

#ifndef SOAP_TYPE_swsf__createSWSResource
#define SOAP_TYPE_swsf__createSWSResource (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_swsf__createSWSResource(struct soap*, struct swsf__createSWSResource *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_swsf__createSWSResource(struct soap*, const struct swsf__createSWSResource *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_swsf__createSWSResource(struct soap*, const struct swsf__createSWSResource *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_swsf__createSWSResource(struct soap*, const char*, int, const struct swsf__createSWSResource *, const char*);
SOAP_FMAC3 struct swsf__createSWSResource * SOAP_FMAC4 soap_get_swsf__createSWSResource(struct soap*, struct swsf__createSWSResource *, const char*, const char*);
SOAP_FMAC3 struct swsf__createSWSResource * SOAP_FMAC4 soap_in_swsf__createSWSResource(struct soap*, const char*, struct swsf__createSWSResource *, const char*);

#ifndef SOAP_TYPE_swsf__createSWSResourceResponse
#define SOAP_TYPE_swsf__createSWSResourceResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_swsf__createSWSResourceResponse(struct soap*, struct swsf__createSWSResourceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_swsf__createSWSResourceResponse(struct soap*, const struct swsf__createSWSResourceResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_swsf__createSWSResourceResponse(struct soap*, const struct swsf__createSWSResourceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_swsf__createSWSResourceResponse(struct soap*, const char*, int, const struct swsf__createSWSResourceResponse *, const char*);
SOAP_FMAC3 struct swsf__createSWSResourceResponse * SOAP_FMAC4 soap_get_swsf__createSWSResourceResponse(struct soap*, struct swsf__createSWSResourceResponse *, const char*, const char*);
SOAP_FMAC3 struct swsf__createSWSResourceResponse * SOAP_FMAC4 soap_in_swsf__createSWSResourceResponse(struct soap*, const char*, struct swsf__createSWSResourceResponse *, const char*);

#ifndef SOAP_TYPE_wsrp__Destroy
#define SOAP_TYPE_wsrp__Destroy (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__Destroy(struct soap*, struct wsrp__Destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__Destroy(struct soap*, const struct wsrp__Destroy *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__Destroy(struct soap*, const struct wsrp__Destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__Destroy(struct soap*, const char*, int, const struct wsrp__Destroy *, const char*);
SOAP_FMAC3 struct wsrp__Destroy * SOAP_FMAC4 soap_get_wsrp__Destroy(struct soap*, struct wsrp__Destroy *, const char*, const char*);
SOAP_FMAC3 struct wsrp__Destroy * SOAP_FMAC4 soap_in_wsrp__Destroy(struct soap*, const char*, struct wsrp__Destroy *, const char*);

#ifndef SOAP_TYPE_sws__PutParamLog
#define SOAP_TYPE_sws__PutParamLog (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__PutParamLog(struct soap*, struct sws__PutParamLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__PutParamLog(struct soap*, const struct sws__PutParamLog *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__PutParamLog(struct soap*, const struct sws__PutParamLog *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__PutParamLog(struct soap*, const char*, int, const struct sws__PutParamLog *, const char*);
SOAP_FMAC3 struct sws__PutParamLog * SOAP_FMAC4 soap_get_sws__PutParamLog(struct soap*, struct sws__PutParamLog *, const char*, const char*);
SOAP_FMAC3 struct sws__PutParamLog * SOAP_FMAC4 soap_in_sws__PutParamLog(struct soap*, const char*, struct sws__PutParamLog *, const char*);

#ifndef SOAP_TYPE_sws__GetParamLog
#define SOAP_TYPE_sws__GetParamLog (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__GetParamLog(struct soap*, struct sws__GetParamLog *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__GetParamLog(struct soap*, const struct sws__GetParamLog *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__GetParamLog(struct soap*, const struct sws__GetParamLog *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__GetParamLog(struct soap*, const char*, int, const struct sws__GetParamLog *, const char*);
SOAP_FMAC3 struct sws__GetParamLog * SOAP_FMAC4 soap_get_sws__GetParamLog(struct soap*, struct sws__GetParamLog *, const char*, const char*);
SOAP_FMAC3 struct sws__GetParamLog * SOAP_FMAC4 soap_in_sws__GetParamLog(struct soap*, const char*, struct sws__GetParamLog *, const char*);

#ifndef SOAP_TYPE_sws__RecordCheckpoint
#define SOAP_TYPE_sws__RecordCheckpoint (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__RecordCheckpoint(struct soap*, struct sws__RecordCheckpoint *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__RecordCheckpoint(struct soap*, const struct sws__RecordCheckpoint *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__RecordCheckpoint(struct soap*, const struct sws__RecordCheckpoint *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__RecordCheckpoint(struct soap*, const char*, int, const struct sws__RecordCheckpoint *, const char*);
SOAP_FMAC3 struct sws__RecordCheckpoint * SOAP_FMAC4 soap_get_sws__RecordCheckpoint(struct soap*, struct sws__RecordCheckpoint *, const char*, const char*);
SOAP_FMAC3 struct sws__RecordCheckpoint * SOAP_FMAC4 soap_in_sws__RecordCheckpoint(struct soap*, const char*, struct sws__RecordCheckpoint *, const char*);

#ifndef SOAP_TYPE_sws__Detach
#define SOAP_TYPE_sws__Detach (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__Detach(struct soap*, struct sws__Detach *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__Detach(struct soap*, const struct sws__Detach *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__Detach(struct soap*, const struct sws__Detach *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__Detach(struct soap*, const char*, int, const struct sws__Detach *, const char*);
SOAP_FMAC3 struct sws__Detach * SOAP_FMAC4 soap_get_sws__Detach(struct soap*, struct sws__Detach *, const char*, const char*);
SOAP_FMAC3 struct sws__Detach * SOAP_FMAC4 soap_in_sws__Detach(struct soap*, const char*, struct sws__Detach *, const char*);

#ifndef SOAP_TYPE_sws__Attach
#define SOAP_TYPE_sws__Attach (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__Attach(struct soap*, struct sws__Attach *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__Attach(struct soap*, const struct sws__Attach *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__Attach(struct soap*, const struct sws__Attach *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__Attach(struct soap*, const char*, int, const struct sws__Attach *, const char*);
SOAP_FMAC3 struct sws__Attach * SOAP_FMAC4 soap_get_sws__Attach(struct soap*, struct sws__Attach *, const char*, const char*);
SOAP_FMAC3 struct sws__Attach * SOAP_FMAC4 soap_in_sws__Attach(struct soap*, const char*, struct sws__Attach *, const char*);

#ifndef SOAP_TYPE_sws__AddChild
#define SOAP_TYPE_sws__AddChild (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__AddChild(struct soap*, struct sws__AddChild *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__AddChild(struct soap*, const struct sws__AddChild *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__AddChild(struct soap*, const struct sws__AddChild *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__AddChild(struct soap*, const char*, int, const struct sws__AddChild *, const char*);
SOAP_FMAC3 struct sws__AddChild * SOAP_FMAC4 soap_get_sws__AddChild(struct soap*, struct sws__AddChild *, const char*, const char*);
SOAP_FMAC3 struct sws__AddChild * SOAP_FMAC4 soap_in_sws__AddChild(struct soap*, const char*, struct sws__AddChild *, const char*);

#ifndef SOAP_TYPE_wsrp__GetResourcePropertyDocument
#define SOAP_TYPE_wsrp__GetResourcePropertyDocument (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__GetResourcePropertyDocument(struct soap*, struct wsrp__GetResourcePropertyDocument *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__GetResourcePropertyDocument(struct soap*, const struct wsrp__GetResourcePropertyDocument *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__GetResourcePropertyDocument(struct soap*, const struct wsrp__GetResourcePropertyDocument *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__GetResourcePropertyDocument(struct soap*, const char*, int, const struct wsrp__GetResourcePropertyDocument *, const char*);
SOAP_FMAC3 struct wsrp__GetResourcePropertyDocument * SOAP_FMAC4 soap_get_wsrp__GetResourcePropertyDocument(struct soap*, struct wsrp__GetResourcePropertyDocument *, const char*, const char*);
SOAP_FMAC3 struct wsrp__GetResourcePropertyDocument * SOAP_FMAC4 soap_in_wsrp__GetResourcePropertyDocument(struct soap*, const char*, struct wsrp__GetResourcePropertyDocument *, const char*);

#ifndef SOAP_TYPE_wsrp__SetResourceProperties
#define SOAP_TYPE_wsrp__SetResourceProperties (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__SetResourceProperties(struct soap*, struct wsrp__SetResourceProperties *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__SetResourceProperties(struct soap*, const struct wsrp__SetResourceProperties *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__SetResourceProperties(struct soap*, const struct wsrp__SetResourceProperties *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__SetResourceProperties(struct soap*, const char*, int, const struct wsrp__SetResourceProperties *, const char*);
SOAP_FMAC3 struct wsrp__SetResourceProperties * SOAP_FMAC4 soap_get_wsrp__SetResourceProperties(struct soap*, struct wsrp__SetResourceProperties *, const char*, const char*);
SOAP_FMAC3 struct wsrp__SetResourceProperties * SOAP_FMAC4 soap_in_wsrp__SetResourceProperties(struct soap*, const char*, struct wsrp__SetResourceProperties *, const char*);

#ifndef SOAP_TYPE_wsrp__GetMultipleResourceProperties
#define SOAP_TYPE_wsrp__GetMultipleResourceProperties (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__GetMultipleResourceProperties(struct soap*, struct wsrp__GetMultipleResourceProperties *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__GetMultipleResourceProperties(struct soap*, const struct wsrp__GetMultipleResourceProperties *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__GetMultipleResourceProperties(struct soap*, const struct wsrp__GetMultipleResourceProperties *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__GetMultipleResourceProperties(struct soap*, const char*, int, const struct wsrp__GetMultipleResourceProperties *, const char*);
SOAP_FMAC3 struct wsrp__GetMultipleResourceProperties * SOAP_FMAC4 soap_get_wsrp__GetMultipleResourceProperties(struct soap*, struct wsrp__GetMultipleResourceProperties *, const char*, const char*);
SOAP_FMAC3 struct wsrp__GetMultipleResourceProperties * SOAP_FMAC4 soap_in_wsrp__GetMultipleResourceProperties(struct soap*, const char*, struct wsrp__GetMultipleResourceProperties *, const char*);

#ifndef SOAP_TYPE___wsrp__GetResourceProperty
#define SOAP_TYPE___wsrp__GetResourceProperty (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___wsrp__GetResourceProperty(struct soap*, struct __wsrp__GetResourceProperty *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___wsrp__GetResourceProperty(struct soap*, const struct __wsrp__GetResourceProperty *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___wsrp__GetResourceProperty(struct soap*, const struct __wsrp__GetResourceProperty *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___wsrp__GetResourceProperty(struct soap*, const char*, int, const struct __wsrp__GetResourceProperty *, const char*);
SOAP_FMAC3 struct __wsrp__GetResourceProperty * SOAP_FMAC4 soap_get___wsrp__GetResourceProperty(struct soap*, struct __wsrp__GetResourceProperty *, const char*, const char*);
SOAP_FMAC3 struct __wsrp__GetResourceProperty * SOAP_FMAC4 soap_in___wsrp__GetResourceProperty(struct soap*, const char*, struct __wsrp__GetResourceProperty *, const char*);

#ifndef SOAP_TYPE_sws__DetachResponse
#define SOAP_TYPE_sws__DetachResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__DetachResponse(struct soap*, struct sws__DetachResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__DetachResponse(struct soap*, const struct sws__DetachResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__DetachResponse(struct soap*, const struct sws__DetachResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__DetachResponse(struct soap*, const char*, int, const struct sws__DetachResponse *, const char*);
SOAP_FMAC3 struct sws__DetachResponse * SOAP_FMAC4 soap_get_sws__DetachResponse(struct soap*, struct sws__DetachResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__DetachResponse * SOAP_FMAC4 soap_in_sws__DetachResponse(struct soap*, const char*, struct sws__DetachResponse *, const char*);

#ifndef SOAP_TYPE_sws__AddChildResponse
#define SOAP_TYPE_sws__AddChildResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__AddChildResponse(struct soap*, struct sws__AddChildResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__AddChildResponse(struct soap*, const struct sws__AddChildResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__AddChildResponse(struct soap*, const struct sws__AddChildResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__AddChildResponse(struct soap*, const char*, int, const struct sws__AddChildResponse *, const char*);
SOAP_FMAC3 struct sws__AddChildResponse * SOAP_FMAC4 soap_get_sws__AddChildResponse(struct soap*, struct sws__AddChildResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__AddChildResponse * SOAP_FMAC4 soap_in_sws__AddChildResponse(struct soap*, const char*, struct sws__AddChildResponse *, const char*);

#ifndef SOAP_TYPE_sws__AddChildRequest
#define SOAP_TYPE_sws__AddChildRequest (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__AddChildRequest(struct soap*, struct sws__AddChildRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__AddChildRequest(struct soap*, const struct sws__AddChildRequest *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__AddChildRequest(struct soap*, const struct sws__AddChildRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__AddChildRequest(struct soap*, const char*, int, const struct sws__AddChildRequest *, const char*);
SOAP_FMAC3 struct sws__AddChildRequest * SOAP_FMAC4 soap_get_sws__AddChildRequest(struct soap*, struct sws__AddChildRequest *, const char*, const char*);
SOAP_FMAC3 struct sws__AddChildRequest * SOAP_FMAC4 soap_in_sws__AddChildRequest(struct soap*, const char*, struct sws__AddChildRequest *, const char*);

#ifndef SOAP_TYPE_wsrp__SetResourcePropertiesResponse
#define SOAP_TYPE_wsrp__SetResourcePropertiesResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__SetResourcePropertiesResponse(struct soap*, struct wsrp__SetResourcePropertiesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__SetResourcePropertiesResponse(struct soap*, const struct wsrp__SetResourcePropertiesResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__SetResourcePropertiesResponse(struct soap*, const struct wsrp__SetResourcePropertiesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__SetResourcePropertiesResponse(struct soap*, const char*, int, const struct wsrp__SetResourcePropertiesResponse *, const char*);
SOAP_FMAC3 struct wsrp__SetResourcePropertiesResponse * SOAP_FMAC4 soap_get_wsrp__SetResourcePropertiesResponse(struct soap*, struct wsrp__SetResourcePropertiesResponse *, const char*, const char*);
SOAP_FMAC3 struct wsrp__SetResourcePropertiesResponse * SOAP_FMAC4 soap_in_wsrp__SetResourcePropertiesResponse(struct soap*, const char*, struct wsrp__SetResourcePropertiesResponse *, const char*);

#ifndef SOAP_TYPE_wsrp__GetMultipleResourcePropertiesRequest
#define SOAP_TYPE_wsrp__GetMultipleResourcePropertiesRequest (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, struct wsrp__GetMultipleResourcePropertiesRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, struct wsrp__GetMultipleResourcePropertiesRequest const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, const struct wsrp__GetMultipleResourcePropertiesRequest *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, const char*, int, const struct wsrp__GetMultipleResourcePropertiesRequest *, const char*);
SOAP_FMAC3 struct wsrp__GetMultipleResourcePropertiesRequest * SOAP_FMAC4 soap_get_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, struct wsrp__GetMultipleResourcePropertiesRequest *, const char*, const char*);
SOAP_FMAC3 struct wsrp__GetMultipleResourcePropertiesRequest * SOAP_FMAC4 soap_in_wsrp__GetMultipleResourcePropertiesRequest(struct soap*, const char*, struct wsrp__GetMultipleResourcePropertiesRequest *, const char*);

#ifndef SOAP_TYPE_wsrp__ResourcePropertyStruct
#define SOAP_TYPE_wsrp__ResourcePropertyStruct (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__ResourcePropertyStruct(struct soap*, struct wsrp__ResourcePropertyStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__ResourcePropertyStruct(struct soap*, const struct wsrp__ResourcePropertyStruct *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__ResourcePropertyStruct(struct soap*, const struct wsrp__ResourcePropertyStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__ResourcePropertyStruct(struct soap*, const char*, int, const struct wsrp__ResourcePropertyStruct *, const char*);
SOAP_FMAC3 struct wsrp__ResourcePropertyStruct * SOAP_FMAC4 soap_get_wsrp__ResourcePropertyStruct(struct soap*, struct wsrp__ResourcePropertyStruct *, const char*, const char*);
SOAP_FMAC3 struct wsrp__ResourcePropertyStruct * SOAP_FMAC4 soap_in_wsrp__ResourcePropertyStruct(struct soap*, const char*, struct wsrp__ResourcePropertyStruct *, const char*);

#ifndef SOAP_TYPE_sws__PutParamLogResponse
#define SOAP_TYPE_sws__PutParamLogResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__PutParamLogResponse(struct soap*, struct sws__PutParamLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__PutParamLogResponse(struct soap*, const struct sws__PutParamLogResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__PutParamLogResponse(struct soap*, const struct sws__PutParamLogResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__PutParamLogResponse(struct soap*, const char*, int, const struct sws__PutParamLogResponse *, const char*);
SOAP_FMAC3 struct sws__PutParamLogResponse * SOAP_FMAC4 soap_get_sws__PutParamLogResponse(struct soap*, struct sws__PutParamLogResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__PutParamLogResponse * SOAP_FMAC4 soap_in_sws__PutParamLogResponse(struct soap*, const char*, struct sws__PutParamLogResponse *, const char*);

#ifndef SOAP_TYPE_wsrp__DestroyResponse
#define SOAP_TYPE_wsrp__DestroyResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsrp__DestroyResponse(struct soap*, struct wsrp__DestroyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsrp__DestroyResponse(struct soap*, const struct wsrp__DestroyResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsrp__DestroyResponse(struct soap*, const struct wsrp__DestroyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsrp__DestroyResponse(struct soap*, const char*, int, const struct wsrp__DestroyResponse *, const char*);
SOAP_FMAC3 struct wsrp__DestroyResponse * SOAP_FMAC4 soap_get_wsrp__DestroyResponse(struct soap*, struct wsrp__DestroyResponse *, const char*, const char*);
SOAP_FMAC3 struct wsrp__DestroyResponse * SOAP_FMAC4 soap_in_wsrp__DestroyResponse(struct soap*, const char*, struct wsrp__DestroyResponse *, const char*);

#ifndef SOAP_TYPE_sws__AttachResponse
#define SOAP_TYPE_sws__AttachResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__AttachResponse(struct soap*, struct sws__AttachResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__AttachResponse(struct soap*, const struct sws__AttachResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__AttachResponse(struct soap*, const struct sws__AttachResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__AttachResponse(struct soap*, const char*, int, const struct sws__AttachResponse *, const char*);
SOAP_FMAC3 struct sws__AttachResponse * SOAP_FMAC4 soap_get_sws__AttachResponse(struct soap*, struct sws__AttachResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__AttachResponse * SOAP_FMAC4 soap_in_sws__AttachResponse(struct soap*, const char*, struct sws__AttachResponse *, const char*);

#ifndef SOAP_TYPE_reg__steerMessage
#define SOAP_TYPE_reg__steerMessage (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_reg__steerMessage(struct soap*, struct reg__steerMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_reg__steerMessage(struct soap*, const struct reg__steerMessage *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_reg__steerMessage(struct soap*, const struct reg__steerMessage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_reg__steerMessage(struct soap*, const char*, int, const struct reg__steerMessage *, const char*);
SOAP_FMAC3 struct reg__steerMessage * SOAP_FMAC4 soap_get_reg__steerMessage(struct soap*, struct reg__steerMessage *, const char*, const char*);
SOAP_FMAC3 struct reg__steerMessage * SOAP_FMAC4 soap_in_reg__steerMessage(struct soap*, const char*, struct reg__steerMessage *, const char*);

#ifndef SOAP_TYPE_reg__supp_cmds
#define SOAP_TYPE_reg__supp_cmds (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_reg__supp_cmds(struct soap*, struct reg__supp_cmds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_reg__supp_cmds(struct soap*, struct reg__supp_cmds const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_reg__supp_cmds(struct soap*, const struct reg__supp_cmds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_reg__supp_cmds(struct soap*, const char*, int, const struct reg__supp_cmds *, const char*);
SOAP_FMAC3 struct reg__supp_cmds * SOAP_FMAC4 soap_get_reg__supp_cmds(struct soap*, struct reg__supp_cmds *, const char*, const char*);
SOAP_FMAC3 struct reg__supp_cmds * SOAP_FMAC4 soap_in_reg__supp_cmds(struct soap*, const char*, struct reg__supp_cmds *, const char*);

#ifndef SOAP_TYPE_reg__Command
#define SOAP_TYPE_reg__Command (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_reg__Command(struct soap*, struct reg__Command *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_reg__Command(struct soap*, const struct reg__Command *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_reg__Command(struct soap*, const struct reg__Command *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_reg__Command(struct soap*, const char*, int, const struct reg__Command *, const char*);
SOAP_FMAC3 struct reg__Command * SOAP_FMAC4 soap_get_reg__Command(struct soap*, struct reg__Command *, const char*, const char*);
SOAP_FMAC3 struct reg__Command * SOAP_FMAC4 soap_in_reg__Command(struct soap*, const char*, struct reg__Command *, const char*);

#ifndef SOAP_TYPE_sws__RecordCheckpointResponse
#define SOAP_TYPE_sws__RecordCheckpointResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__RecordCheckpointResponse(struct soap*, struct sws__RecordCheckpointResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__RecordCheckpointResponse(struct soap*, const struct sws__RecordCheckpointResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__RecordCheckpointResponse(struct soap*, const struct sws__RecordCheckpointResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__RecordCheckpointResponse(struct soap*, const char*, int, const struct sws__RecordCheckpointResponse *, const char*);
SOAP_FMAC3 struct sws__RecordCheckpointResponse * SOAP_FMAC4 soap_get_sws__RecordCheckpointResponse(struct soap*, struct sws__RecordCheckpointResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__RecordCheckpointResponse * SOAP_FMAC4 soap_in_sws__RecordCheckpointResponse(struct soap*, const char*, struct sws__RecordCheckpointResponse *, const char*);

#ifndef SOAP_TYPE_sws__GetParamLogResponse
#define SOAP_TYPE_sws__GetParamLogResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_sws__GetParamLogResponse(struct soap*, struct sws__GetParamLogResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_sws__GetParamLogResponse(struct soap*, const struct sws__GetParamLogResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_sws__GetParamLogResponse(struct soap*, const struct sws__GetParamLogResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_sws__GetParamLogResponse(struct soap*, const char*, int, const struct sws__GetParamLogResponse *, const char*);
SOAP_FMAC3 struct sws__GetParamLogResponse * SOAP_FMAC4 soap_get_sws__GetParamLogResponse(struct soap*, struct sws__GetParamLogResponse *, const char*, const char*);
SOAP_FMAC3 struct sws__GetParamLogResponse * SOAP_FMAC4 soap_in_sws__GetParamLogResponse(struct soap*, const char*, struct sws__GetParamLogResponse *, const char*);

#ifndef SOAP_TYPE_epr
#define SOAP_TYPE_epr (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_epr(struct soap*, struct epr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_epr(struct soap*, const struct epr *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_epr(struct soap*, const struct epr *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_epr(struct soap*, const char*, int, const struct epr *, const char*);
SOAP_FMAC3 struct epr * SOAP_FMAC4 soap_get_epr(struct soap*, struct epr *, const char*, const char*);
SOAP_FMAC3 struct epr * SOAP_FMAC4 soap_in_epr(struct soap*, const char*, struct epr *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (102)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTocptn__addNodeResponse
#define SOAP_TYPE_PointerTocptn__addNodeResponse (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocptn__addNodeResponse(struct soap*, struct cptn__addNodeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocptn__addNodeResponse(struct soap*, struct cptn__addNodeResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocptn__addNodeResponse(struct soap*, const char *, int, struct cptn__addNodeResponse *const*, const char *);
SOAP_FMAC3 struct cptn__addNodeResponse ** SOAP_FMAC4 soap_get_PointerTocptn__addNodeResponse(struct soap*, struct cptn__addNodeResponse **, const char*, const char*);
SOAP_FMAC3 struct cptn__addNodeResponse ** SOAP_FMAC4 soap_in_PointerTocptn__addNodeResponse(struct soap*, const char*, struct cptn__addNodeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocptn__destroyResponse
#define SOAP_TYPE_PointerTocptn__destroyResponse (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocptn__destroyResponse(struct soap*, struct cptn__destroyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocptn__destroyResponse(struct soap*, struct cptn__destroyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocptn__destroyResponse(struct soap*, const char *, int, struct cptn__destroyResponse *const*, const char *);
SOAP_FMAC3 struct cptn__destroyResponse ** SOAP_FMAC4 soap_get_PointerTocptn__destroyResponse(struct soap*, struct cptn__destroyResponse **, const char*, const char*);
SOAP_FMAC3 struct cptn__destroyResponse ** SOAP_FMAC4 soap_in_PointerTocptn__destroyResponse(struct soap*, const char*, struct cptn__destroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocpt__getActiveTreesResponse
#define SOAP_TYPE_PointerTocpt__getActiveTreesResponse (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocpt__getActiveTreesResponse(struct soap*, struct cpt__getActiveTreesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocpt__getActiveTreesResponse(struct soap*, struct cpt__getActiveTreesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocpt__getActiveTreesResponse(struct soap*, const char *, int, struct cpt__getActiveTreesResponse *const*, const char *);
SOAP_FMAC3 struct cpt__getActiveTreesResponse ** SOAP_FMAC4 soap_get_PointerTocpt__getActiveTreesResponse(struct soap*, struct cpt__getActiveTreesResponse **, const char*, const char*);
SOAP_FMAC3 struct cpt__getActiveTreesResponse ** SOAP_FMAC4 soap_in_PointerTocpt__getActiveTreesResponse(struct soap*, const char*, struct cpt__getActiveTreesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocpt__destroyResponse
#define SOAP_TYPE_PointerTocpt__destroyResponse (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocpt__destroyResponse(struct soap*, struct cpt__destroyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocpt__destroyResponse(struct soap*, struct cpt__destroyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocpt__destroyResponse(struct soap*, const char *, int, struct cpt__destroyResponse *const*, const char *);
SOAP_FMAC3 struct cpt__destroyResponse ** SOAP_FMAC4 soap_get_PointerTocpt__destroyResponse(struct soap*, struct cpt__destroyResponse **, const char*, const char*);
SOAP_FMAC3 struct cpt__destroyResponse ** SOAP_FMAC4 soap_in_PointerTocpt__destroyResponse(struct soap*, const char*, struct cpt__destroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocpt__findByHandleResponse
#define SOAP_TYPE_PointerTocpt__findByHandleResponse (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocpt__findByHandleResponse(struct soap*, struct cpt__findByHandleResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocpt__findByHandleResponse(struct soap*, struct cpt__findByHandleResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocpt__findByHandleResponse(struct soap*, const char *, int, struct cpt__findByHandleResponse *const*, const char *);
SOAP_FMAC3 struct cpt__findByHandleResponse ** SOAP_FMAC4 soap_get_PointerTocpt__findByHandleResponse(struct soap*, struct cpt__findByHandleResponse **, const char*, const char*);
SOAP_FMAC3 struct cpt__findByHandleResponse ** SOAP_FMAC4 soap_in_PointerTocpt__findByHandleResponse(struct soap*, const char*, struct cpt__findByHandleResponse **, const char*);

#ifndef SOAP_TYPE_PointerTocpt__createNewTreeResponse
#define SOAP_TYPE_PointerTocpt__createNewTreeResponse (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocpt__createNewTreeResponse(struct soap*, struct cpt__createNewTreeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocpt__createNewTreeResponse(struct soap*, struct cpt__createNewTreeResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocpt__createNewTreeResponse(struct soap*, const char *, int, struct cpt__createNewTreeResponse *const*, const char *);
SOAP_FMAC3 struct cpt__createNewTreeResponse ** SOAP_FMAC4 soap_get_PointerTocpt__createNewTreeResponse(struct soap*, struct cpt__createNewTreeResponse **, const char*, const char*);
SOAP_FMAC3 struct cpt__createNewTreeResponse ** SOAP_FMAC4 soap_in_PointerTocpt__createNewTreeResponse(struct soap*, const char*, struct cpt__createNewTreeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTorsg__AddResponse
#define SOAP_TYPE_PointerTorsg__AddResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTorsg__AddResponse(struct soap*, struct rsg__AddResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTorsg__AddResponse(struct soap*, struct rsg__AddResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTorsg__AddResponse(struct soap*, const char *, int, struct rsg__AddResponse *const*, const char *);
SOAP_FMAC3 struct rsg__AddResponse ** SOAP_FMAC4 soap_get_PointerTorsg__AddResponse(struct soap*, struct rsg__AddResponse **, const char*, const char*);
SOAP_FMAC3 struct rsg__AddResponse ** SOAP_FMAC4 soap_in_PointerTorsg__AddResponse(struct soap*, const char*, struct rsg__AddResponse **, const char*);

#ifndef SOAP_TYPE_PointerToswsf__createSWSResourceResponse
#define SOAP_TYPE_PointerToswsf__createSWSResourceResponse (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToswsf__createSWSResourceResponse(struct soap*, struct swsf__createSWSResourceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToswsf__createSWSResourceResponse(struct soap*, struct swsf__createSWSResourceResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToswsf__createSWSResourceResponse(struct soap*, const char *, int, struct swsf__createSWSResourceResponse *const*, const char *);
SOAP_FMAC3 struct swsf__createSWSResourceResponse ** SOAP_FMAC4 soap_get_PointerToswsf__createSWSResourceResponse(struct soap*, struct swsf__createSWSResourceResponse **, const char*, const char*);
SOAP_FMAC3 struct swsf__createSWSResourceResponse ** SOAP_FMAC4 soap_in_PointerToswsf__createSWSResourceResponse(struct soap*, const char*, struct swsf__createSWSResourceResponse **, const char*);

#ifndef SOAP_TYPE_PointerTowsrp__DestroyResponse
#define SOAP_TYPE_PointerTowsrp__DestroyResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsrp__DestroyResponse(struct soap*, struct wsrp__DestroyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsrp__DestroyResponse(struct soap*, struct wsrp__DestroyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsrp__DestroyResponse(struct soap*, const char *, int, struct wsrp__DestroyResponse *const*, const char *);
SOAP_FMAC3 struct wsrp__DestroyResponse ** SOAP_FMAC4 soap_get_PointerTowsrp__DestroyResponse(struct soap*, struct wsrp__DestroyResponse **, const char*, const char*);
SOAP_FMAC3 struct wsrp__DestroyResponse ** SOAP_FMAC4 soap_in_PointerTowsrp__DestroyResponse(struct soap*, const char*, struct wsrp__DestroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__PutParamLogResponse
#define SOAP_TYPE_PointerTosws__PutParamLogResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__PutParamLogResponse(struct soap*, struct sws__PutParamLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__PutParamLogResponse(struct soap*, struct sws__PutParamLogResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__PutParamLogResponse(struct soap*, const char *, int, struct sws__PutParamLogResponse *const*, const char *);
SOAP_FMAC3 struct sws__PutParamLogResponse ** SOAP_FMAC4 soap_get_PointerTosws__PutParamLogResponse(struct soap*, struct sws__PutParamLogResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__PutParamLogResponse ** SOAP_FMAC4 soap_in_PointerTosws__PutParamLogResponse(struct soap*, const char*, struct sws__PutParamLogResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__GetParamLogResponse
#define SOAP_TYPE_PointerTosws__GetParamLogResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__GetParamLogResponse(struct soap*, struct sws__GetParamLogResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__GetParamLogResponse(struct soap*, struct sws__GetParamLogResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__GetParamLogResponse(struct soap*, const char *, int, struct sws__GetParamLogResponse *const*, const char *);
SOAP_FMAC3 struct sws__GetParamLogResponse ** SOAP_FMAC4 soap_get_PointerTosws__GetParamLogResponse(struct soap*, struct sws__GetParamLogResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__GetParamLogResponse ** SOAP_FMAC4 soap_in_PointerTosws__GetParamLogResponse(struct soap*, const char*, struct sws__GetParamLogResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__RecordCheckpointResponse
#define SOAP_TYPE_PointerTosws__RecordCheckpointResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__RecordCheckpointResponse(struct soap*, struct sws__RecordCheckpointResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__RecordCheckpointResponse(struct soap*, struct sws__RecordCheckpointResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__RecordCheckpointResponse(struct soap*, const char *, int, struct sws__RecordCheckpointResponse *const*, const char *);
SOAP_FMAC3 struct sws__RecordCheckpointResponse ** SOAP_FMAC4 soap_get_PointerTosws__RecordCheckpointResponse(struct soap*, struct sws__RecordCheckpointResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__RecordCheckpointResponse ** SOAP_FMAC4 soap_in_PointerTosws__RecordCheckpointResponse(struct soap*, const char*, struct sws__RecordCheckpointResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__DetachResponse
#define SOAP_TYPE_PointerTosws__DetachResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__DetachResponse(struct soap*, struct sws__DetachResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__DetachResponse(struct soap*, struct sws__DetachResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__DetachResponse(struct soap*, const char *, int, struct sws__DetachResponse *const*, const char *);
SOAP_FMAC3 struct sws__DetachResponse ** SOAP_FMAC4 soap_get_PointerTosws__DetachResponse(struct soap*, struct sws__DetachResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__DetachResponse ** SOAP_FMAC4 soap_in_PointerTosws__DetachResponse(struct soap*, const char*, struct sws__DetachResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__AttachResponse
#define SOAP_TYPE_PointerTosws__AttachResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__AttachResponse(struct soap*, struct sws__AttachResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__AttachResponse(struct soap*, struct sws__AttachResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__AttachResponse(struct soap*, const char *, int, struct sws__AttachResponse *const*, const char *);
SOAP_FMAC3 struct sws__AttachResponse ** SOAP_FMAC4 soap_get_PointerTosws__AttachResponse(struct soap*, struct sws__AttachResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__AttachResponse ** SOAP_FMAC4 soap_in_PointerTosws__AttachResponse(struct soap*, const char*, struct sws__AttachResponse **, const char*);

#ifndef SOAP_TYPE_PointerTosws__AddChildResponse
#define SOAP_TYPE_PointerTosws__AddChildResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTosws__AddChildResponse(struct soap*, struct sws__AddChildResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTosws__AddChildResponse(struct soap*, struct sws__AddChildResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTosws__AddChildResponse(struct soap*, const char *, int, struct sws__AddChildResponse *const*, const char *);
SOAP_FMAC3 struct sws__AddChildResponse ** SOAP_FMAC4 soap_get_PointerTosws__AddChildResponse(struct soap*, struct sws__AddChildResponse **, const char*, const char*);
SOAP_FMAC3 struct sws__AddChildResponse ** SOAP_FMAC4 soap_in_PointerTosws__AddChildResponse(struct soap*, const char*, struct sws__AddChildResponse **, const char*);

#ifndef SOAP_TYPE_PointerTowsrp__SetResourcePropertiesResponse
#define SOAP_TYPE_PointerTowsrp__SetResourcePropertiesResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsrp__SetResourcePropertiesResponse(struct soap*, struct wsrp__SetResourcePropertiesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsrp__SetResourcePropertiesResponse(struct soap*, struct wsrp__SetResourcePropertiesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsrp__SetResourcePropertiesResponse(struct soap*, const char *, int, struct wsrp__SetResourcePropertiesResponse *const*, const char *);
SOAP_FMAC3 struct wsrp__SetResourcePropertiesResponse ** SOAP_FMAC4 soap_get_PointerTowsrp__SetResourcePropertiesResponse(struct soap*, struct wsrp__SetResourcePropertiesResponse **, const char*, const char*);
SOAP_FMAC3 struct wsrp__SetResourcePropertiesResponse ** SOAP_FMAC4 soap_in_PointerTowsrp__SetResourcePropertiesResponse(struct soap*, const char*, struct wsrp__SetResourcePropertiesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTowsrp__ResourcePropertyStruct
#define SOAP_TYPE_PointerTowsrp__ResourcePropertyStruct (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsrp__ResourcePropertyStruct(struct soap*, struct wsrp__ResourcePropertyStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsrp__ResourcePropertyStruct(struct soap*, struct wsrp__ResourcePropertyStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsrp__ResourcePropertyStruct(struct soap*, const char *, int, struct wsrp__ResourcePropertyStruct *const*, const char *);
SOAP_FMAC3 struct wsrp__ResourcePropertyStruct ** SOAP_FMAC4 soap_get_PointerTowsrp__ResourcePropertyStruct(struct soap*, struct wsrp__ResourcePropertyStruct **, const char*, const char*);
SOAP_FMAC3 struct wsrp__ResourcePropertyStruct ** SOAP_FMAC4 soap_in_PointerTowsrp__ResourcePropertyStruct(struct soap*, const char*, struct wsrp__ResourcePropertyStruct **, const char*);

#ifndef SOAP_TYPE_PointerToreg__Command
#define SOAP_TYPE_PointerToreg__Command (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToreg__Command(struct soap*, struct reg__Command *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToreg__Command(struct soap*, struct reg__Command *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToreg__Command(struct soap*, const char *, int, struct reg__Command *const*, const char *);
SOAP_FMAC3 struct reg__Command ** SOAP_FMAC4 soap_get_PointerToreg__Command(struct soap*, struct reg__Command **, const char*, const char*);
SOAP_FMAC3 struct reg__Command ** SOAP_FMAC4 soap_in_PointerToreg__Command(struct soap*, const char*, struct reg__Command **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
