/* soapH.h
   Generated by gSOAP 2.2.3b from SGS.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soapH_H
#define soapH_H
#include "stdsoap2.h"
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (1)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_byte(struct soap*, char *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (2)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_int(struct soap*, int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (3)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (4)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (5)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef SOAP_TYPE_tns__PutControl
#define SOAP_TYPE_tns__PutControl (6)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__PutControl(struct soap*, struct tns__PutControl const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__PutControl(struct soap*, const struct tns__PutControl *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__PutControl(struct soap*, struct tns__PutControl *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__PutControl(struct soap*, struct tns__PutControl *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__PutControl(struct soap*, const char*, int, const struct tns__PutControl *, const char*);
SOAP_FMAC1 struct tns__PutControl * SOAP_FMAC2 soap_get_tns__PutControl(struct soap*, struct tns__PutControl *, const char*, const char*);
SOAP_FMAC1 struct tns__PutControl * SOAP_FMAC2 soap_in_tns__PutControl(struct soap*, const char*, struct tns__PutControl *, const char*);

#ifndef SOAP_TYPE_tns__Destroy
#define SOAP_TYPE_tns__Destroy (7)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Destroy(struct soap*, struct tns__Destroy const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Destroy(struct soap*, const struct tns__Destroy *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Destroy(struct soap*, struct tns__Destroy *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Destroy(struct soap*, struct tns__Destroy *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Destroy(struct soap*, const char*, int, const struct tns__Destroy *, const char*);
SOAP_FMAC1 struct tns__Destroy * SOAP_FMAC2 soap_get_tns__Destroy(struct soap*, struct tns__Destroy *, const char*, const char*);
SOAP_FMAC1 struct tns__Destroy * SOAP_FMAC2 soap_in_tns__Destroy(struct soap*, const char*, struct tns__Destroy *, const char*);

#ifndef SOAP_TYPE_tns__AppStart
#define SOAP_TYPE_tns__AppStart (8)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppStart(struct soap*, struct tns__AppStart const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppStart(struct soap*, const struct tns__AppStart *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppStart(struct soap*, struct tns__AppStart *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppStart(struct soap*, struct tns__AppStart *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppStart(struct soap*, const char*, int, const struct tns__AppStart *, const char*);
SOAP_FMAC1 struct tns__AppStart * SOAP_FMAC2 soap_get_tns__AppStart(struct soap*, struct tns__AppStart *, const char*, const char*);
SOAP_FMAC1 struct tns__AppStart * SOAP_FMAC2 soap_in_tns__AppStart(struct soap*, const char*, struct tns__AppStart *, const char*);

#ifndef SOAP_TYPE_tns__PutStatus
#define SOAP_TYPE_tns__PutStatus (9)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__PutStatus(struct soap*, struct tns__PutStatus const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__PutStatus(struct soap*, const struct tns__PutStatus *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__PutStatus(struct soap*, struct tns__PutStatus *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__PutStatus(struct soap*, struct tns__PutStatus *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__PutStatus(struct soap*, const char*, int, const struct tns__PutStatus *, const char*);
SOAP_FMAC1 struct tns__PutStatus * SOAP_FMAC2 soap_get_tns__PutStatus(struct soap*, struct tns__PutStatus *, const char*, const char*);
SOAP_FMAC1 struct tns__PutStatus * SOAP_FMAC2 soap_in_tns__PutStatus(struct soap*, const char*, struct tns__PutStatus *, const char*);

#ifndef SOAP_TYPE_tns__Pause
#define SOAP_TYPE_tns__Pause (10)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Pause(struct soap*, struct tns__Pause const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Pause(struct soap*, const struct tns__Pause *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Pause(struct soap*, struct tns__Pause *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Pause(struct soap*, struct tns__Pause *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Pause(struct soap*, const char*, int, const struct tns__Pause *, const char*);
SOAP_FMAC1 struct tns__Pause * SOAP_FMAC2 soap_get_tns__Pause(struct soap*, struct tns__Pause *, const char*, const char*);
SOAP_FMAC1 struct tns__Pause * SOAP_FMAC2 soap_in_tns__Pause(struct soap*, const char*, struct tns__Pause *, const char*);

#ifndef SOAP_TYPE_tns__GetNotifications
#define SOAP_TYPE_tns__GetNotifications (11)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetNotifications(struct soap*, struct tns__GetNotifications const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetNotifications(struct soap*, const struct tns__GetNotifications *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetNotifications(struct soap*, struct tns__GetNotifications *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetNotifications(struct soap*, struct tns__GetNotifications *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetNotifications(struct soap*, const char*, int, const struct tns__GetNotifications *, const char*);
SOAP_FMAC1 struct tns__GetNotifications * SOAP_FMAC2 soap_get_tns__GetNotifications(struct soap*, struct tns__GetNotifications *, const char*, const char*);
SOAP_FMAC1 struct tns__GetNotifications * SOAP_FMAC2 soap_in_tns__GetNotifications(struct soap*, const char*, struct tns__GetNotifications *, const char*);

#ifndef SOAP_TYPE_tns__Stop
#define SOAP_TYPE_tns__Stop (12)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Stop(struct soap*, struct tns__Stop const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Stop(struct soap*, const struct tns__Stop *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Stop(struct soap*, struct tns__Stop *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Stop(struct soap*, struct tns__Stop *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Stop(struct soap*, const char*, int, const struct tns__Stop *, const char*);
SOAP_FMAC1 struct tns__Stop * SOAP_FMAC2 soap_get_tns__Stop(struct soap*, struct tns__Stop *, const char*, const char*);
SOAP_FMAC1 struct tns__Stop * SOAP_FMAC2 soap_in_tns__Stop(struct soap*, const char*, struct tns__Stop *, const char*);

#ifndef SOAP_TYPE_tns__GetControl
#define SOAP_TYPE_tns__GetControl (13)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetControl(struct soap*, struct tns__GetControl const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetControl(struct soap*, const struct tns__GetControl *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetControl(struct soap*, struct tns__GetControl *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetControl(struct soap*, struct tns__GetControl *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetControl(struct soap*, const char*, int, const struct tns__GetControl *, const char*);
SOAP_FMAC1 struct tns__GetControl * SOAP_FMAC2 soap_get_tns__GetControl(struct soap*, struct tns__GetControl *, const char*, const char*);
SOAP_FMAC1 struct tns__GetControl * SOAP_FMAC2 soap_in_tns__GetControl(struct soap*, const char*, struct tns__GetControl *, const char*);

#ifndef SOAP_TYPE_tns__Resume
#define SOAP_TYPE_tns__Resume (14)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Resume(struct soap*, struct tns__Resume const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Resume(struct soap*, const struct tns__Resume *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Resume(struct soap*, struct tns__Resume *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Resume(struct soap*, struct tns__Resume *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Resume(struct soap*, const char*, int, const struct tns__Resume *, const char*);
SOAP_FMAC1 struct tns__Resume * SOAP_FMAC2 soap_get_tns__Resume(struct soap*, struct tns__Resume *, const char*, const char*);
SOAP_FMAC1 struct tns__Resume * SOAP_FMAC2 soap_in_tns__Resume(struct soap*, const char*, struct tns__Resume *, const char*);

#ifndef SOAP_TYPE_tns__AppStop
#define SOAP_TYPE_tns__AppStop (15)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppStop(struct soap*, struct tns__AppStop const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppStop(struct soap*, const struct tns__AppStop *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppStop(struct soap*, struct tns__AppStop *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppStop(struct soap*, struct tns__AppStop *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppStop(struct soap*, const char*, int, const struct tns__AppStop *, const char*);
SOAP_FMAC1 struct tns__AppStop * SOAP_FMAC2 soap_get_tns__AppStop(struct soap*, struct tns__AppStop *, const char*, const char*);
SOAP_FMAC1 struct tns__AppStop * SOAP_FMAC2 soap_in_tns__AppStop(struct soap*, const char*, struct tns__AppStop *, const char*);

#ifndef SOAP_TYPE_tns__SetTerminationTime
#define SOAP_TYPE_tns__SetTerminationTime (16)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__SetTerminationTime(struct soap*, struct tns__SetTerminationTime const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__SetTerminationTime(struct soap*, const struct tns__SetTerminationTime *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__SetTerminationTime(struct soap*, struct tns__SetTerminationTime *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__SetTerminationTime(struct soap*, struct tns__SetTerminationTime *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__SetTerminationTime(struct soap*, const char*, int, const struct tns__SetTerminationTime *, const char*);
SOAP_FMAC1 struct tns__SetTerminationTime * SOAP_FMAC2 soap_get_tns__SetTerminationTime(struct soap*, struct tns__SetTerminationTime *, const char*, const char*);
SOAP_FMAC1 struct tns__SetTerminationTime * SOAP_FMAC2 soap_in_tns__SetTerminationTime(struct soap*, const char*, struct tns__SetTerminationTime *, const char*);

#ifndef SOAP_TYPE_tns__GetNthDataSource
#define SOAP_TYPE_tns__GetNthDataSource (17)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetNthDataSource(struct soap*, struct tns__GetNthDataSource const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetNthDataSource(struct soap*, const struct tns__GetNthDataSource *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetNthDataSource(struct soap*, struct tns__GetNthDataSource *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetNthDataSource(struct soap*, struct tns__GetNthDataSource *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetNthDataSource(struct soap*, const char*, int, const struct tns__GetNthDataSource *, const char*);
SOAP_FMAC1 struct tns__GetNthDataSource * SOAP_FMAC2 soap_get_tns__GetNthDataSource(struct soap*, struct tns__GetNthDataSource *, const char*, const char*);
SOAP_FMAC1 struct tns__GetNthDataSource * SOAP_FMAC2 soap_in_tns__GetNthDataSource(struct soap*, const char*, struct tns__GetNthDataSource *, const char*);

#ifndef SOAP_TYPE_tns__GetStatus
#define SOAP_TYPE_tns__GetStatus (18)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetStatus(struct soap*, struct tns__GetStatus const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetStatus(struct soap*, const struct tns__GetStatus *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetStatus(struct soap*, struct tns__GetStatus *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetStatus(struct soap*, struct tns__GetStatus *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetStatus(struct soap*, const char*, int, const struct tns__GetStatus *, const char*);
SOAP_FMAC1 struct tns__GetStatus * SOAP_FMAC2 soap_get_tns__GetStatus(struct soap*, struct tns__GetStatus *, const char*, const char*);
SOAP_FMAC1 struct tns__GetStatus * SOAP_FMAC2 soap_in_tns__GetStatus(struct soap*, const char*, struct tns__GetStatus *, const char*);

#ifndef SOAP_TYPE_tns__FindServiceData
#define SOAP_TYPE_tns__FindServiceData (19)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__FindServiceData(struct soap*, struct tns__FindServiceData const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__FindServiceData(struct soap*, const struct tns__FindServiceData *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__FindServiceData(struct soap*, struct tns__FindServiceData *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__FindServiceData(struct soap*, struct tns__FindServiceData *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__FindServiceData(struct soap*, const char*, int, const struct tns__FindServiceData *, const char*);
SOAP_FMAC1 struct tns__FindServiceData * SOAP_FMAC2 soap_get_tns__FindServiceData(struct soap*, struct tns__FindServiceData *, const char*, const char*);
SOAP_FMAC1 struct tns__FindServiceData * SOAP_FMAC2 soap_in_tns__FindServiceData(struct soap*, const char*, struct tns__FindServiceData *, const char*);

#ifndef SOAP_TYPE_tns__Detach
#define SOAP_TYPE_tns__Detach (20)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Detach(struct soap*, struct tns__Detach const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Detach(struct soap*, const struct tns__Detach *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Detach(struct soap*, struct tns__Detach *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Detach(struct soap*, struct tns__Detach *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Detach(struct soap*, const char*, int, const struct tns__Detach *, const char*);
SOAP_FMAC1 struct tns__Detach * SOAP_FMAC2 soap_get_tns__Detach(struct soap*, struct tns__Detach *, const char*, const char*);
SOAP_FMAC1 struct tns__Detach * SOAP_FMAC2 soap_in_tns__Detach(struct soap*, const char*, struct tns__Detach *, const char*);

#ifndef SOAP_TYPE_tns__SetServiceData
#define SOAP_TYPE_tns__SetServiceData (21)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__SetServiceData(struct soap*, struct tns__SetServiceData const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__SetServiceData(struct soap*, const struct tns__SetServiceData *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__SetServiceData(struct soap*, struct tns__SetServiceData *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__SetServiceData(struct soap*, struct tns__SetServiceData *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__SetServiceData(struct soap*, const char*, int, const struct tns__SetServiceData *, const char*);
SOAP_FMAC1 struct tns__SetServiceData * SOAP_FMAC2 soap_get_tns__SetServiceData(struct soap*, struct tns__SetServiceData *, const char*, const char*);
SOAP_FMAC1 struct tns__SetServiceData * SOAP_FMAC2 soap_in_tns__SetServiceData(struct soap*, const char*, struct tns__SetServiceData *, const char*);

#ifndef SOAP_TYPE_tns__Attach
#define SOAP_TYPE_tns__Attach (22)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__Attach(struct soap*, struct tns__Attach const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__Attach(struct soap*, const struct tns__Attach *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__Attach(struct soap*, struct tns__Attach *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__Attach(struct soap*, struct tns__Attach *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__Attach(struct soap*, const char*, int, const struct tns__Attach *, const char*);
SOAP_FMAC1 struct tns__Attach * SOAP_FMAC2 soap_get_tns__Attach(struct soap*, struct tns__Attach *, const char*, const char*);
SOAP_FMAC1 struct tns__Attach * SOAP_FMAC2 soap_in_tns__Attach(struct soap*, const char*, struct tns__Attach *, const char*);

#ifndef SOAP_TYPE_tns__AppDetach
#define SOAP_TYPE_tns__AppDetach (23)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppDetach(struct soap*, struct tns__AppDetach const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppDetach(struct soap*, const struct tns__AppDetach *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppDetach(struct soap*, struct tns__AppDetach *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppDetach(struct soap*, struct tns__AppDetach *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppDetach(struct soap*, const char*, int, const struct tns__AppDetach *, const char*);
SOAP_FMAC1 struct tns__AppDetach * SOAP_FMAC2 soap_get_tns__AppDetach(struct soap*, struct tns__AppDetach *, const char*, const char*);
SOAP_FMAC1 struct tns__AppDetach * SOAP_FMAC2 soap_in_tns__AppDetach(struct soap*, const char*, struct tns__AppDetach *, const char*);

#ifndef SOAP_TYPE_tns__GetControlResponse
#define SOAP_TYPE_tns__GetControlResponse (24)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetControlResponse(struct soap*, struct tns__GetControlResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetControlResponse(struct soap*, const struct tns__GetControlResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetControlResponse(struct soap*, struct tns__GetControlResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetControlResponse(struct soap*, struct tns__GetControlResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetControlResponse(struct soap*, const char*, int, const struct tns__GetControlResponse *, const char*);
SOAP_FMAC1 struct tns__GetControlResponse * SOAP_FMAC2 soap_get_tns__GetControlResponse(struct soap*, struct tns__GetControlResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__GetControlResponse * SOAP_FMAC2 soap_in_tns__GetControlResponse(struct soap*, const char*, struct tns__GetControlResponse *, const char*);

#ifndef SOAP_TYPE_tns__DestroyResponse
#define SOAP_TYPE_tns__DestroyResponse (25)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__DestroyResponse(struct soap*, struct tns__DestroyResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__DestroyResponse(struct soap*, const struct tns__DestroyResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__DestroyResponse(struct soap*, struct tns__DestroyResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__DestroyResponse(struct soap*, struct tns__DestroyResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__DestroyResponse(struct soap*, const char*, int, const struct tns__DestroyResponse *, const char*);
SOAP_FMAC1 struct tns__DestroyResponse * SOAP_FMAC2 soap_get_tns__DestroyResponse(struct soap*, struct tns__DestroyResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__DestroyResponse * SOAP_FMAC2 soap_in_tns__DestroyResponse(struct soap*, const char*, struct tns__DestroyResponse *, const char*);

#ifndef SOAP_TYPE_tns__GetNotificationsResponse
#define SOAP_TYPE_tns__GetNotificationsResponse (26)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetNotificationsResponse(struct soap*, const struct tns__GetNotificationsResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetNotificationsResponse(struct soap*, const char*, int, const struct tns__GetNotificationsResponse *, const char*);
SOAP_FMAC1 struct tns__GetNotificationsResponse * SOAP_FMAC2 soap_get_tns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__GetNotificationsResponse * SOAP_FMAC2 soap_in_tns__GetNotificationsResponse(struct soap*, const char*, struct tns__GetNotificationsResponse *, const char*);

#ifndef SOAP_TYPE_tns__PauseResponse
#define SOAP_TYPE_tns__PauseResponse (27)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__PauseResponse(struct soap*, struct tns__PauseResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__PauseResponse(struct soap*, const struct tns__PauseResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__PauseResponse(struct soap*, struct tns__PauseResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__PauseResponse(struct soap*, struct tns__PauseResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__PauseResponse(struct soap*, const char*, int, const struct tns__PauseResponse *, const char*);
SOAP_FMAC1 struct tns__PauseResponse * SOAP_FMAC2 soap_get_tns__PauseResponse(struct soap*, struct tns__PauseResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__PauseResponse * SOAP_FMAC2 soap_in_tns__PauseResponse(struct soap*, const char*, struct tns__PauseResponse *, const char*);

#ifndef SOAP_TYPE_tns__SetTerminationTimeResponse
#define SOAP_TYPE_tns__SetTerminationTimeResponse (28)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__SetTerminationTimeResponse(struct soap*, const struct tns__SetTerminationTimeResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__SetTerminationTimeResponse(struct soap*, const char*, int, const struct tns__SetTerminationTimeResponse *, const char*);
SOAP_FMAC1 struct tns__SetTerminationTimeResponse * SOAP_FMAC2 soap_get_tns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__SetTerminationTimeResponse * SOAP_FMAC2 soap_in_tns__SetTerminationTimeResponse(struct soap*, const char*, struct tns__SetTerminationTimeResponse *, const char*);

#ifndef SOAP_TYPE_tns__AttachResponse
#define SOAP_TYPE_tns__AttachResponse (29)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AttachResponse(struct soap*, struct tns__AttachResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AttachResponse(struct soap*, const struct tns__AttachResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AttachResponse(struct soap*, struct tns__AttachResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AttachResponse(struct soap*, struct tns__AttachResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AttachResponse(struct soap*, const char*, int, const struct tns__AttachResponse *, const char*);
SOAP_FMAC1 struct tns__AttachResponse * SOAP_FMAC2 soap_get_tns__AttachResponse(struct soap*, struct tns__AttachResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__AttachResponse * SOAP_FMAC2 soap_in_tns__AttachResponse(struct soap*, const char*, struct tns__AttachResponse *, const char*);

#ifndef SOAP_TYPE_tns__PutStatusResponse
#define SOAP_TYPE_tns__PutStatusResponse (30)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__PutStatusResponse(struct soap*, const struct tns__PutStatusResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__PutStatusResponse(struct soap*, const char*, int, const struct tns__PutStatusResponse *, const char*);
SOAP_FMAC1 struct tns__PutStatusResponse * SOAP_FMAC2 soap_get_tns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__PutStatusResponse * SOAP_FMAC2 soap_in_tns__PutStatusResponse(struct soap*, const char*, struct tns__PutStatusResponse *, const char*);

#ifndef SOAP_TYPE_tns__PutControlResponse
#define SOAP_TYPE_tns__PutControlResponse (31)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__PutControlResponse(struct soap*, struct tns__PutControlResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__PutControlResponse(struct soap*, const struct tns__PutControlResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__PutControlResponse(struct soap*, struct tns__PutControlResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__PutControlResponse(struct soap*, struct tns__PutControlResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__PutControlResponse(struct soap*, const char*, int, const struct tns__PutControlResponse *, const char*);
SOAP_FMAC1 struct tns__PutControlResponse * SOAP_FMAC2 soap_get_tns__PutControlResponse(struct soap*, struct tns__PutControlResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__PutControlResponse * SOAP_FMAC2 soap_in_tns__PutControlResponse(struct soap*, const char*, struct tns__PutControlResponse *, const char*);

#ifndef SOAP_TYPE_tns__AppDetachResponse
#define SOAP_TYPE_tns__AppDetachResponse (32)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppDetachResponse(struct soap*, const struct tns__AppDetachResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppDetachResponse(struct soap*, const char*, int, const struct tns__AppDetachResponse *, const char*);
SOAP_FMAC1 struct tns__AppDetachResponse * SOAP_FMAC2 soap_get_tns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__AppDetachResponse * SOAP_FMAC2 soap_in_tns__AppDetachResponse(struct soap*, const char*, struct tns__AppDetachResponse *, const char*);

#ifndef SOAP_TYPE_tns__ResumeResponse
#define SOAP_TYPE_tns__ResumeResponse (33)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__ResumeResponse(struct soap*, struct tns__ResumeResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__ResumeResponse(struct soap*, const struct tns__ResumeResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__ResumeResponse(struct soap*, struct tns__ResumeResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__ResumeResponse(struct soap*, struct tns__ResumeResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__ResumeResponse(struct soap*, const char*, int, const struct tns__ResumeResponse *, const char*);
SOAP_FMAC1 struct tns__ResumeResponse * SOAP_FMAC2 soap_get_tns__ResumeResponse(struct soap*, struct tns__ResumeResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__ResumeResponse * SOAP_FMAC2 soap_in_tns__ResumeResponse(struct soap*, const char*, struct tns__ResumeResponse *, const char*);

#ifndef SOAP_TYPE_tns__FindServiceDataResponse
#define SOAP_TYPE_tns__FindServiceDataResponse (34)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__FindServiceDataResponse(struct soap*, const struct tns__FindServiceDataResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__FindServiceDataResponse(struct soap*, const char*, int, const struct tns__FindServiceDataResponse *, const char*);
SOAP_FMAC1 struct tns__FindServiceDataResponse * SOAP_FMAC2 soap_get_tns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__FindServiceDataResponse * SOAP_FMAC2 soap_in_tns__FindServiceDataResponse(struct soap*, const char*, struct tns__FindServiceDataResponse *, const char*);

#ifndef SOAP_TYPE_tns__GetNthDataSourceResponse
#define SOAP_TYPE_tns__GetNthDataSourceResponse (35)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetNthDataSourceResponse(struct soap*, const struct tns__GetNthDataSourceResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetNthDataSourceResponse(struct soap*, const char*, int, const struct tns__GetNthDataSourceResponse *, const char*);
SOAP_FMAC1 struct tns__GetNthDataSourceResponse * SOAP_FMAC2 soap_get_tns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__GetNthDataSourceResponse * SOAP_FMAC2 soap_in_tns__GetNthDataSourceResponse(struct soap*, const char*, struct tns__GetNthDataSourceResponse *, const char*);

#ifndef SOAP_TYPE_tns__DetachResponse
#define SOAP_TYPE_tns__DetachResponse (36)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__DetachResponse(struct soap*, struct tns__DetachResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__DetachResponse(struct soap*, const struct tns__DetachResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__DetachResponse(struct soap*, struct tns__DetachResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__DetachResponse(struct soap*, struct tns__DetachResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__DetachResponse(struct soap*, const char*, int, const struct tns__DetachResponse *, const char*);
SOAP_FMAC1 struct tns__DetachResponse * SOAP_FMAC2 soap_get_tns__DetachResponse(struct soap*, struct tns__DetachResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__DetachResponse * SOAP_FMAC2 soap_in_tns__DetachResponse(struct soap*, const char*, struct tns__DetachResponse *, const char*);

#ifndef SOAP_TYPE_tns__AppStopResponse
#define SOAP_TYPE_tns__AppStopResponse (37)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppStopResponse(struct soap*, struct tns__AppStopResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppStopResponse(struct soap*, const struct tns__AppStopResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppStopResponse(struct soap*, struct tns__AppStopResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppStopResponse(struct soap*, struct tns__AppStopResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppStopResponse(struct soap*, const char*, int, const struct tns__AppStopResponse *, const char*);
SOAP_FMAC1 struct tns__AppStopResponse * SOAP_FMAC2 soap_get_tns__AppStopResponse(struct soap*, struct tns__AppStopResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__AppStopResponse * SOAP_FMAC2 soap_in_tns__AppStopResponse(struct soap*, const char*, struct tns__AppStopResponse *, const char*);

#ifndef SOAP_TYPE_tns__SetServiceDataResponse
#define SOAP_TYPE_tns__SetServiceDataResponse (38)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__SetServiceDataResponse(struct soap*, const struct tns__SetServiceDataResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__SetServiceDataResponse(struct soap*, const char*, int, const struct tns__SetServiceDataResponse *, const char*);
SOAP_FMAC1 struct tns__SetServiceDataResponse * SOAP_FMAC2 soap_get_tns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__SetServiceDataResponse * SOAP_FMAC2 soap_in_tns__SetServiceDataResponse(struct soap*, const char*, struct tns__SetServiceDataResponse *, const char*);

#ifndef SOAP_TYPE_tns__StopResponse
#define SOAP_TYPE_tns__StopResponse (39)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__StopResponse(struct soap*, struct tns__StopResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__StopResponse(struct soap*, const struct tns__StopResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__StopResponse(struct soap*, struct tns__StopResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__StopResponse(struct soap*, struct tns__StopResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__StopResponse(struct soap*, const char*, int, const struct tns__StopResponse *, const char*);
SOAP_FMAC1 struct tns__StopResponse * SOAP_FMAC2 soap_get_tns__StopResponse(struct soap*, struct tns__StopResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__StopResponse * SOAP_FMAC2 soap_in_tns__StopResponse(struct soap*, const char*, struct tns__StopResponse *, const char*);

#ifndef SOAP_TYPE_tns__AppStartResponse
#define SOAP_TYPE_tns__AppStartResponse (40)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__AppStartResponse(struct soap*, struct tns__AppStartResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__AppStartResponse(struct soap*, const struct tns__AppStartResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__AppStartResponse(struct soap*, struct tns__AppStartResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__AppStartResponse(struct soap*, struct tns__AppStartResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__AppStartResponse(struct soap*, const char*, int, const struct tns__AppStartResponse *, const char*);
SOAP_FMAC1 struct tns__AppStartResponse * SOAP_FMAC2 soap_get_tns__AppStartResponse(struct soap*, struct tns__AppStartResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__AppStartResponse * SOAP_FMAC2 soap_in_tns__AppStartResponse(struct soap*, const char*, struct tns__AppStartResponse *, const char*);

#ifndef SOAP_TYPE_tns__GetStatusResponse
#define SOAP_TYPE_tns__GetStatusResponse (41)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_tns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_tns__GetStatusResponse(struct soap*, const struct tns__GetStatusResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_tns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse *);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_tns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_tns__GetStatusResponse(struct soap*, const char*, int, const struct tns__GetStatusResponse *, const char*);
SOAP_FMAC1 struct tns__GetStatusResponse * SOAP_FMAC2 soap_get_tns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse *, const char*, const char*);
SOAP_FMAC1 struct tns__GetStatusResponse * SOAP_FMAC2 soap_in_tns__GetStatusResponse(struct soap*, const char*, struct tns__GetStatusResponse *, const char*);

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (42)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code ** SOAP_FMAC2 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef SOAP_TYPE_PointerTotns__PutControlResponse
#define SOAP_TYPE_PointerTotns__PutControlResponse (43)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__PutControlResponse(struct soap*, struct tns__PutControlResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__PutControlResponse(struct soap*, struct tns__PutControlResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__PutControlResponse(struct soap*, struct tns__PutControlResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__PutControlResponse(struct soap*, struct tns__PutControlResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__PutControlResponse(struct soap*, const char *, int, struct tns__PutControlResponse *const*, const char *);
SOAP_FMAC1 struct tns__PutControlResponse ** SOAP_FMAC2 soap_get_PointerTotns__PutControlResponse(struct soap*, struct tns__PutControlResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__PutControlResponse ** SOAP_FMAC2 soap_in_PointerTotns__PutControlResponse(struct soap*, const char*, struct tns__PutControlResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__DestroyResponse
#define SOAP_TYPE_PointerTotns__DestroyResponse (44)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__DestroyResponse(struct soap*, struct tns__DestroyResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__DestroyResponse(struct soap*, struct tns__DestroyResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__DestroyResponse(struct soap*, struct tns__DestroyResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__DestroyResponse(struct soap*, struct tns__DestroyResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__DestroyResponse(struct soap*, const char *, int, struct tns__DestroyResponse *const*, const char *);
SOAP_FMAC1 struct tns__DestroyResponse ** SOAP_FMAC2 soap_get_PointerTotns__DestroyResponse(struct soap*, struct tns__DestroyResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__DestroyResponse ** SOAP_FMAC2 soap_in_PointerTotns__DestroyResponse(struct soap*, const char*, struct tns__DestroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__AppStartResponse
#define SOAP_TYPE_PointerTotns__AppStartResponse (45)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__AppStartResponse(struct soap*, struct tns__AppStartResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__AppStartResponse(struct soap*, struct tns__AppStartResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__AppStartResponse(struct soap*, struct tns__AppStartResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__AppStartResponse(struct soap*, struct tns__AppStartResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__AppStartResponse(struct soap*, const char *, int, struct tns__AppStartResponse *const*, const char *);
SOAP_FMAC1 struct tns__AppStartResponse ** SOAP_FMAC2 soap_get_PointerTotns__AppStartResponse(struct soap*, struct tns__AppStartResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__AppStartResponse ** SOAP_FMAC2 soap_in_PointerTotns__AppStartResponse(struct soap*, const char*, struct tns__AppStartResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__PutStatusResponse
#define SOAP_TYPE_PointerTotns__PutStatusResponse (46)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__PutStatusResponse(struct soap*, const char *, int, struct tns__PutStatusResponse *const*, const char *);
SOAP_FMAC1 struct tns__PutStatusResponse ** SOAP_FMAC2 soap_get_PointerTotns__PutStatusResponse(struct soap*, struct tns__PutStatusResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__PutStatusResponse ** SOAP_FMAC2 soap_in_PointerTotns__PutStatusResponse(struct soap*, const char*, struct tns__PutStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__PauseResponse
#define SOAP_TYPE_PointerTotns__PauseResponse (47)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__PauseResponse(struct soap*, struct tns__PauseResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__PauseResponse(struct soap*, struct tns__PauseResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__PauseResponse(struct soap*, struct tns__PauseResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__PauseResponse(struct soap*, struct tns__PauseResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__PauseResponse(struct soap*, const char *, int, struct tns__PauseResponse *const*, const char *);
SOAP_FMAC1 struct tns__PauseResponse ** SOAP_FMAC2 soap_get_PointerTotns__PauseResponse(struct soap*, struct tns__PauseResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__PauseResponse ** SOAP_FMAC2 soap_in_PointerTotns__PauseResponse(struct soap*, const char*, struct tns__PauseResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__GetNotificationsResponse
#define SOAP_TYPE_PointerTotns__GetNotificationsResponse (48)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__GetNotificationsResponse(struct soap*, const char *, int, struct tns__GetNotificationsResponse *const*, const char *);
SOAP_FMAC1 struct tns__GetNotificationsResponse ** SOAP_FMAC2 soap_get_PointerTotns__GetNotificationsResponse(struct soap*, struct tns__GetNotificationsResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__GetNotificationsResponse ** SOAP_FMAC2 soap_in_PointerTotns__GetNotificationsResponse(struct soap*, const char*, struct tns__GetNotificationsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__StopResponse
#define SOAP_TYPE_PointerTotns__StopResponse (49)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__StopResponse(struct soap*, struct tns__StopResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__StopResponse(struct soap*, struct tns__StopResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__StopResponse(struct soap*, struct tns__StopResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__StopResponse(struct soap*, struct tns__StopResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__StopResponse(struct soap*, const char *, int, struct tns__StopResponse *const*, const char *);
SOAP_FMAC1 struct tns__StopResponse ** SOAP_FMAC2 soap_get_PointerTotns__StopResponse(struct soap*, struct tns__StopResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__StopResponse ** SOAP_FMAC2 soap_in_PointerTotns__StopResponse(struct soap*, const char*, struct tns__StopResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__GetControlResponse
#define SOAP_TYPE_PointerTotns__GetControlResponse (50)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__GetControlResponse(struct soap*, struct tns__GetControlResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__GetControlResponse(struct soap*, struct tns__GetControlResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__GetControlResponse(struct soap*, struct tns__GetControlResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__GetControlResponse(struct soap*, struct tns__GetControlResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__GetControlResponse(struct soap*, const char *, int, struct tns__GetControlResponse *const*, const char *);
SOAP_FMAC1 struct tns__GetControlResponse ** SOAP_FMAC2 soap_get_PointerTotns__GetControlResponse(struct soap*, struct tns__GetControlResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__GetControlResponse ** SOAP_FMAC2 soap_in_PointerTotns__GetControlResponse(struct soap*, const char*, struct tns__GetControlResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__ResumeResponse
#define SOAP_TYPE_PointerTotns__ResumeResponse (51)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__ResumeResponse(struct soap*, struct tns__ResumeResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__ResumeResponse(struct soap*, struct tns__ResumeResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__ResumeResponse(struct soap*, struct tns__ResumeResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__ResumeResponse(struct soap*, struct tns__ResumeResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__ResumeResponse(struct soap*, const char *, int, struct tns__ResumeResponse *const*, const char *);
SOAP_FMAC1 struct tns__ResumeResponse ** SOAP_FMAC2 soap_get_PointerTotns__ResumeResponse(struct soap*, struct tns__ResumeResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__ResumeResponse ** SOAP_FMAC2 soap_in_PointerTotns__ResumeResponse(struct soap*, const char*, struct tns__ResumeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__AppStopResponse
#define SOAP_TYPE_PointerTotns__AppStopResponse (52)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__AppStopResponse(struct soap*, struct tns__AppStopResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__AppStopResponse(struct soap*, struct tns__AppStopResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__AppStopResponse(struct soap*, struct tns__AppStopResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__AppStopResponse(struct soap*, struct tns__AppStopResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__AppStopResponse(struct soap*, const char *, int, struct tns__AppStopResponse *const*, const char *);
SOAP_FMAC1 struct tns__AppStopResponse ** SOAP_FMAC2 soap_get_PointerTotns__AppStopResponse(struct soap*, struct tns__AppStopResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__AppStopResponse ** SOAP_FMAC2 soap_in_PointerTotns__AppStopResponse(struct soap*, const char*, struct tns__AppStopResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__SetTerminationTimeResponse
#define SOAP_TYPE_PointerTotns__SetTerminationTimeResponse (53)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__SetTerminationTimeResponse(struct soap*, const char *, int, struct tns__SetTerminationTimeResponse *const*, const char *);
SOAP_FMAC1 struct tns__SetTerminationTimeResponse ** SOAP_FMAC2 soap_get_PointerTotns__SetTerminationTimeResponse(struct soap*, struct tns__SetTerminationTimeResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__SetTerminationTimeResponse ** SOAP_FMAC2 soap_in_PointerTotns__SetTerminationTimeResponse(struct soap*, const char*, struct tns__SetTerminationTimeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__GetNthDataSourceResponse
#define SOAP_TYPE_PointerTotns__GetNthDataSourceResponse (54)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__GetNthDataSourceResponse(struct soap*, const char *, int, struct tns__GetNthDataSourceResponse *const*, const char *);
SOAP_FMAC1 struct tns__GetNthDataSourceResponse ** SOAP_FMAC2 soap_get_PointerTotns__GetNthDataSourceResponse(struct soap*, struct tns__GetNthDataSourceResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__GetNthDataSourceResponse ** SOAP_FMAC2 soap_in_PointerTotns__GetNthDataSourceResponse(struct soap*, const char*, struct tns__GetNthDataSourceResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__GetStatusResponse
#define SOAP_TYPE_PointerTotns__GetStatusResponse (55)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__GetStatusResponse(struct soap*, const char *, int, struct tns__GetStatusResponse *const*, const char *);
SOAP_FMAC1 struct tns__GetStatusResponse ** SOAP_FMAC2 soap_get_PointerTotns__GetStatusResponse(struct soap*, struct tns__GetStatusResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__GetStatusResponse ** SOAP_FMAC2 soap_in_PointerTotns__GetStatusResponse(struct soap*, const char*, struct tns__GetStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__FindServiceDataResponse
#define SOAP_TYPE_PointerTotns__FindServiceDataResponse (56)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__FindServiceDataResponse(struct soap*, const char *, int, struct tns__FindServiceDataResponse *const*, const char *);
SOAP_FMAC1 struct tns__FindServiceDataResponse ** SOAP_FMAC2 soap_get_PointerTotns__FindServiceDataResponse(struct soap*, struct tns__FindServiceDataResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__FindServiceDataResponse ** SOAP_FMAC2 soap_in_PointerTotns__FindServiceDataResponse(struct soap*, const char*, struct tns__FindServiceDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__DetachResponse
#define SOAP_TYPE_PointerTotns__DetachResponse (57)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__DetachResponse(struct soap*, struct tns__DetachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__DetachResponse(struct soap*, struct tns__DetachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__DetachResponse(struct soap*, struct tns__DetachResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__DetachResponse(struct soap*, struct tns__DetachResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__DetachResponse(struct soap*, const char *, int, struct tns__DetachResponse *const*, const char *);
SOAP_FMAC1 struct tns__DetachResponse ** SOAP_FMAC2 soap_get_PointerTotns__DetachResponse(struct soap*, struct tns__DetachResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__DetachResponse ** SOAP_FMAC2 soap_in_PointerTotns__DetachResponse(struct soap*, const char*, struct tns__DetachResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__SetServiceDataResponse
#define SOAP_TYPE_PointerTotns__SetServiceDataResponse (58)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__SetServiceDataResponse(struct soap*, const char *, int, struct tns__SetServiceDataResponse *const*, const char *);
SOAP_FMAC1 struct tns__SetServiceDataResponse ** SOAP_FMAC2 soap_get_PointerTotns__SetServiceDataResponse(struct soap*, struct tns__SetServiceDataResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__SetServiceDataResponse ** SOAP_FMAC2 soap_in_PointerTotns__SetServiceDataResponse(struct soap*, const char*, struct tns__SetServiceDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__AttachResponse
#define SOAP_TYPE_PointerTotns__AttachResponse (59)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__AttachResponse(struct soap*, struct tns__AttachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__AttachResponse(struct soap*, struct tns__AttachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__AttachResponse(struct soap*, struct tns__AttachResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__AttachResponse(struct soap*, struct tns__AttachResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__AttachResponse(struct soap*, const char *, int, struct tns__AttachResponse *const*, const char *);
SOAP_FMAC1 struct tns__AttachResponse ** SOAP_FMAC2 soap_get_PointerTotns__AttachResponse(struct soap*, struct tns__AttachResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__AttachResponse ** SOAP_FMAC2 soap_in_PointerTotns__AttachResponse(struct soap*, const char*, struct tns__AttachResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__AppDetachResponse
#define SOAP_TYPE_PointerTotns__AppDetachResponse (60)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTotns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTotns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTotns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse **);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_PointerTotns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_PointerTotns__AppDetachResponse(struct soap*, const char *, int, struct tns__AppDetachResponse *const*, const char *);
SOAP_FMAC1 struct tns__AppDetachResponse ** SOAP_FMAC2 soap_get_PointerTotns__AppDetachResponse(struct soap*, struct tns__AppDetachResponse **, const char*, const char*);
SOAP_FMAC1 struct tns__AppDetachResponse ** SOAP_FMAC2 soap_in_PointerTotns__AppDetachResponse(struct soap*, const char*, struct tns__AppDetachResponse **, const char*);

#ifndef SOAP_TYPE_xsdl__PutStatusRequest
#define SOAP_TYPE_xsdl__PutStatusRequest (61)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PutStatusRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PutStatusRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PutStatusRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PutStatusRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PutStatusRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PutStatusRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PutStatusRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__StopRequest
#define SOAP_TYPE_xsdl__StopRequest (62)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__StopRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__StopRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__StopRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__StopRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__StopRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__StopRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__StopRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__DetachRequest
#define SOAP_TYPE_xsdl__DetachRequest (63)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__DetachRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__DetachRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__DetachRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__DetachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__DetachRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__DetachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__DetachRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppDetachRequest
#define SOAP_TYPE_xsdl__AppDetachRequest (64)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppDetachRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppDetachRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppDetachRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppDetachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppDetachRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppDetachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppDetachRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetNthDataSourceRequest
#define SOAP_TYPE_xsdl__GetNthDataSourceRequest (65)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetNthDataSourceRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetNthDataSourceRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetNthDataSourceRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetNthDataSourceRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetNthDataSourceRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetNthDataSourceRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetNthDataSourceRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AttachRequest
#define SOAP_TYPE_xsdl__AttachRequest (66)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AttachRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AttachRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AttachRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AttachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AttachRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AttachRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AttachRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetNthDataSourceResponse
#define SOAP_TYPE_xsdl__GetNthDataSourceResponse (67)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetNthDataSourceResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetNthDataSourceResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetNthDataSourceResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetNthDataSourceResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetNthDataSourceResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetNthDataSourceResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetNthDataSourceResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppStartRequest
#define SOAP_TYPE_xsdl__AppStartRequest (68)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppStartRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppStartRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppStartRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppStartRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppStartRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppStartRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppStartRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppDetachResponse
#define SOAP_TYPE_xsdl__AppDetachResponse (69)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppDetachResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppDetachResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppDetachResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppDetachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppDetachResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppDetachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppDetachResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__PutStatusResponse
#define SOAP_TYPE_xsdl__PutStatusResponse (70)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PutStatusResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PutStatusResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PutStatusResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PutStatusResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PutStatusResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PutStatusResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PutStatusResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AttachResponse
#define SOAP_TYPE_xsdl__AttachResponse (71)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AttachResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AttachResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AttachResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AttachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AttachResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AttachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AttachResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetControlRequest
#define SOAP_TYPE_xsdl__GetControlRequest (72)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetControlRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetControlRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetControlRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetControlRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetControlRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetControlRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetControlRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__ResumeResponse
#define SOAP_TYPE_xsdl__ResumeResponse (73)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__ResumeResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__ResumeResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__ResumeResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__ResumeResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__ResumeResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__ResumeResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__ResumeResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__PutControlResponse
#define SOAP_TYPE_xsdl__PutControlResponse (74)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PutControlResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PutControlResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PutControlResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PutControlResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PutControlResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PutControlResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PutControlResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__SetTerminationTimeResponse
#define SOAP_TYPE_xsdl__SetTerminationTimeResponse (75)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__SetTerminationTimeResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__SetTerminationTimeResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__SetTerminationTimeResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__SetTerminationTimeResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__SetTerminationTimeResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__SetTerminationTimeResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__SetTerminationTimeResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__PauseResponse
#define SOAP_TYPE_xsdl__PauseResponse (76)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PauseResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PauseResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PauseResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PauseResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PauseResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PauseResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PauseResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__SetServiceDataRequest
#define SOAP_TYPE_xsdl__SetServiceDataRequest (77)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__SetServiceDataRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__SetServiceDataRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__SetServiceDataRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__SetServiceDataRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__SetServiceDataRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__SetServiceDataRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__SetServiceDataRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetStatusRequest
#define SOAP_TYPE_xsdl__GetStatusRequest (78)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetStatusRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetStatusRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetStatusRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetStatusRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetStatusRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetStatusRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetStatusRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__FindServiceDataRequest
#define SOAP_TYPE_xsdl__FindServiceDataRequest (79)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__FindServiceDataRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__FindServiceDataRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__FindServiceDataRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__FindServiceDataRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__FindServiceDataRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__FindServiceDataRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__FindServiceDataRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__SetServiceDataResponse
#define SOAP_TYPE_xsdl__SetServiceDataResponse (80)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__SetServiceDataResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__SetServiceDataResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__SetServiceDataResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__SetServiceDataResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__SetServiceDataResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__SetServiceDataResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__SetServiceDataResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__StopResponse
#define SOAP_TYPE_xsdl__StopResponse (81)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__StopResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__StopResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__StopResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__StopResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__StopResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__StopResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__StopResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__DetachResponse
#define SOAP_TYPE_xsdl__DetachResponse (82)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__DetachResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__DetachResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__DetachResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__DetachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__DetachResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__DetachResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__DetachResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__ResumeRequest
#define SOAP_TYPE_xsdl__ResumeRequest (83)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__ResumeRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__ResumeRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__ResumeRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__ResumeRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__ResumeRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__ResumeRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__ResumeRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppStopResponse
#define SOAP_TYPE_xsdl__AppStopResponse (84)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppStopResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppStopResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppStopResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppStopResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppStopResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppStopResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppStopResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppStartResponse
#define SOAP_TYPE_xsdl__AppStartResponse (85)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppStartResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppStartResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppStartResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppStartResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppStartResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppStartResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppStartResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__AppStopRequest
#define SOAP_TYPE_xsdl__AppStopRequest (86)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__AppStopRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__AppStopRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__AppStopRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__AppStopRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__AppStopRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__AppStopRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__AppStopRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__PauseRequest
#define SOAP_TYPE_xsdl__PauseRequest (87)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PauseRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PauseRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PauseRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PauseRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PauseRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PauseRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PauseRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetNotificationsRequest
#define SOAP_TYPE_xsdl__GetNotificationsRequest (88)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetNotificationsRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetNotificationsRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetNotificationsRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetNotificationsRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetNotificationsRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetNotificationsRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetNotificationsRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetStatusResponse
#define SOAP_TYPE_xsdl__GetStatusResponse (89)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetStatusResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetStatusResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetStatusResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetStatusResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetStatusResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetStatusResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetStatusResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetNotificationsResponse
#define SOAP_TYPE_xsdl__GetNotificationsResponse (90)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetNotificationsResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetNotificationsResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetNotificationsResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetNotificationsResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetNotificationsResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetNotificationsResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetNotificationsResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__SetTerminationTimeRequest
#define SOAP_TYPE_xsdl__SetTerminationTimeRequest (91)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__SetTerminationTimeRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__SetTerminationTimeRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__SetTerminationTimeRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__SetTerminationTimeRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__SetTerminationTimeRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__SetTerminationTimeRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__SetTerminationTimeRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__DestroyRequest
#define SOAP_TYPE_xsdl__DestroyRequest (92)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__DestroyRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__DestroyRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__DestroyRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__DestroyRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__DestroyRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__DestroyRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__DestroyRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__FindServiceDataResponse
#define SOAP_TYPE_xsdl__FindServiceDataResponse (93)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__FindServiceDataResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__FindServiceDataResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__FindServiceDataResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__FindServiceDataResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__FindServiceDataResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__FindServiceDataResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__FindServiceDataResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__PutControlRequest
#define SOAP_TYPE_xsdl__PutControlRequest (94)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__PutControlRequest(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__PutControlRequest(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__PutControlRequest(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__PutControlRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__PutControlRequest(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__PutControlRequest(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__PutControlRequest(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__GetControlResponse
#define SOAP_TYPE_xsdl__GetControlResponse (95)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__GetControlResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__GetControlResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__GetControlResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__GetControlResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__GetControlResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__GetControlResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__GetControlResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsdl__DestroyResponse
#define SOAP_TYPE_xsdl__DestroyResponse (96)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsdl__DestroyResponse(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsdl__DestroyResponse(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsdl__DestroyResponse(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsdl__DestroyResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsdl__DestroyResponse(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsdl__DestroyResponse(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsdl__DestroyResponse(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (97)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__integer(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__integer(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__integer(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (98)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (99)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_string(struct soap*, char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC1 int SOAP_FMAC2 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_string(struct soap*, const char*, char **, const char*);
#ifdef __cplusplus
}
#endif
#endif

/* end of soapH.h */
